### ISSUE TITLE
Report status to Github via Checks API

### ISSUE THREAD

**Issue by kvuchkov** [openfaas/openfaas-cloud#107]
Github Checks API offers a great in-app experience for CI/CD by showing rich information about different build steps along with some actions (e.g. re-run). It is a superset of the status API. 

This would make openfaas-cloud feel even more natively integrated with GitHub by showing most of the information directly in the app. Moreover, there will be a separate tab on pull requests to support more advanced development flows.

**Constraints**
- It is important to keep the interoperability of openfaas-cloud, i.e. consider future integrations with other SCM providers that do not offer the same style of API.
- Build logs will still need to be persisted (e.g. in S3). The Checks API should be considered an _output_ and not a _source_ build information.

**Comment by martindekov** [comment]
Derek close: Implemented in #114
