### ISSUE TITLE
Allow AWS S3 bucket for pipeline-log

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#116]
## Expected Behaviour

Allow usage of AWS S3 bucket for pipeline-log

## Current Behaviour

Needs to accept:
- TLS flag
- custom "bucket name"
- possibly "region" too

## Possible Solution

Enable two more env-vars to configure bucket name and whether to set TLS.

Code:

https://github.com/openfaas/openfaas-cloud/blob/master/pipeline-log/handler.go

**Comment by alexellis** [comment]
@affix do you want to take this one? Have you got time?

**Comment by affix** [comment]
@alexellis I'll take it on this weekend :)

**Comment by alexellis** [comment]
That would be appreciated. Can you update the readme too?

**Comment by alexellis** [comment]
The bucket name is hard-coded to `pipeline` for use with Minio right now. So if someone puts `martin-staging-pipeline` we need to use that instead of the hard-coded string for read/write. For Minio I think it's safe to default if no value is given in the YAML for the environmental variable.

**Comment by alexellis** [comment]
Checked with @affix - no progress made over weekend. Had a call with @martindekov + @bartsmykla who are going to pick it up this week.
