### ISSUE TITLE
sdk.ReportStatus treated as singleton

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#117]
This relates to the `sdk.ReportStatus` function from @s8sg which is being treated as a singleton (anti-patten) and is preventing unit testing. There may be other similar pieces of code, but we should start with big pieces like this.

## Expected Behaviour

Code using `sdk.ReportStatus` cannot be unit tested since it cannot be swapped out. This should be changed into a factory pattern.

## Current Behaviour

Whatever code has used `sdk.ReportStatus` cannot be tested.

## Possible Solution

Something like this:

```
// For use in code when testing (needs to be injected)
statusReporter := sdk.CreateStatusReporter(sdk.ReportType.Void)

// For regular use for deployment in live system
statusReporter := sdk.CreateStatusReporter(sdk.ReportType.Live)
```

## Steps to Reproduce (for bugs)

1. Try to write a unit test for "github-push"'s handle() function
2. Get errors

## Context

Unit test coverage is key to stability and preventing regression.

**Comment by alexellis** [comment]
Hey @kvuchkov do you have any suggestions on this?

**Comment by s8sg** [comment]
I'm not sure what exactly you meant by `singleton` here. You can have multiple status objects.

**Comment by s8sg** [comment]
I still didn't understood one point `ReportStatus` is not sticky to the code, to be honest the wrapper `ReportStatus` is added over sdk on the function level so that we can control the status behaviour by `enable/disable` status.

**Comment by alexellis** [comment]
Personal opinions aside, do you understand how to make the change I'm asking for or would more detail help?

**Comment by alexellis** [comment]
The same issue exists for `sdk.PostAudit` and `sdk.ReadSecret` - the example I've picked is the tip of the iceberg which is preventing unit-testing.

**Comment by alexellis** [comment]
Here's an example of how to fix the issues introduced by `sdk.PostAudit`:

```go
type Audit interface {
	Post(sdk.AuditEvent) error
}

type NilLogger struct {
}

func (l *NilLogger) Post(auditEvent sdk.AuditEvent) error {
	return nil
}

type AuditLogger struct {
}

func (l *AuditLogger) Post(auditEvent sdk.AuditEvent) error {
	sdk.PostAudit(auditEvent)
	return nil
}

var audit Audit

// Handle a serverless request
func Handle(req []byte) string {

	// Create or inject audit based upon context

	event := os.Getenv("Http_X_Github_Event")
	if event != "push" {

		auditEvent := sdk.AuditEvent{
			Message: "bad event: " + event,
			Source:  Source,
		}
		audit.Post(auditEvent)
		// sdk.PostAudit(auditEvent)

		return fmt.Sprintf("%s cannot handle event: %s", Source, event)
	}
}
```

**Comment by s8sg** [comment]
I think I got it wrong, I was mostly focusing on how `ReportStatus` is implemented. Using `stub` implementation for testing sounds good, rather than disabling the feature. 
```
// For use in code when testing (needs to be injected)
statusReporter := sdk.CreateStatusReporter(sdk.ReportType.Void)

// For regular use for deployment in live system
statusReporter := sdk.CreateStatusReporter(sdk.ReportType.Live)
```
Somehow with This line I got the impression the stub reporter is a part of sdk. It can be a part of the test case only. 
```
sdk.SetStatusReporter(myDummyReporter)
// default is always `sdk.ReportType.Live`
```

**Comment by alexellis** [comment]
I've implemented a way to stub this and the tests pass / adding coverage:

https://github.com/openfaas/openfaas-cloud/blob/master/github-push/handler_test.go

The next step is to add a secret store stub since one of the tests is blocked at that point now.

https://github.com/openfaas/openfaas-cloud/blob/master/github-push/handler_test.go#L82
