### ISSUE TITLE
Signing releases?

### ISSUE THREAD

**Issue by Lewiscowles1986** [openfaas/openfaas-cloud#13]
It'd be a good idea to implement some sort of signing, even if it's sending a separate list of files related to the built function. I Understand you could defer some of this to encrypted transport to ensure nothing has tampered with in-transit, but perhaps a way to communicate with the server "hey here's a new valid hash for a release".

**Comment by Lewiscowles1986** [comment]
AFAIK docker registry's will accept any valid image, even overwriting old ones as a function of being updateable. As OpenFaaS uses Docker, this could leave a function gateway vulnerable to an attack where a new docker function is pushed to the registry tagged. 

By storing valid image signatures (somewhere, no idea about where yet) for a named and tagged function, in a whitelist (ideal), or globally (not ideal but still ensures valid whitelisted docker images), protects against such an attack. 

Although it makes deployment less trivial, you can protect against that sort of attack, and ensure accidental pushes don't happen (I think win, win).

Specifics, I don't have. I have not specced out data structures, or even a formal system flow. More experienced people might just think this is paranoid, or unnecessary or have feedback on improving it, or specific implementations.

**Comment by alexellis** [comment]
This is what "content trust" is meant to resolve, but has problems in practice. 

https://docs.docker.com/engine/security/trust/content_trust/#push-trusted-content

I"ll mark this for #revisit. It's a good point and I wonder what other projects are doing?
