### ISSUE TITLE
Add node8 express template to the `git-tar` function

### ISSUE THREAD

**Issue by kenfdev** [openfaas/openfaas-cloud#136]
It would be nice to be able to serve SPAs in OpenFaaS Cloud. To be able to do that, the new `of-watchdog` would be a requirement because the function would need to serve the assets (index.html, *.js, *.css, etc.) and set proper `Content-Type` depending on the file type.

## Expected Behaviour

The [node8-express-template](https://github.com/openfaas-incubator/of-watchdog) should work with OpenFaaS Cloud, too.

## Current Behaviour

Only the default templates are supported.

## Possible Solution

Pull the templates before the shrinkwrap in the `git-tar` function.

## Context

I'm trying to serve a React SPA with OpenFaaS Cloud.

**Comment by kenfdev** [comment]
Derek add label: proposal

**Comment by kenfdev** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Derek close: released
