### ISSUE TITLE
garbage-collect must use internal trust

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#140]
## Expected Behaviour

garbage-collect should validate all requests using the internal trust secret

## Current Behaviour

It doesn't which means if you have the URL you may be able to delete functions

## Possible Solution

@martindekov to investigate

**Comment by bartsmykla** [comment]
Derek assign: me

**Comment by alexellis** [comment]
@martindekov please take this as a top priority.

**Comment by alexellis** [comment]
Thanks Bart
