### ISSUE TITLE
Feature: OAuth2.0

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#145]
According to the roadmap we should use an OAuth2.0 integration to personalise/protect the dashboard page.

## Current behaviour:

Dashboard pages are open

## New behaviour

User must first log-in with GitHub

I expect this to be implemented within the `router` component in a stateless way using the Code Grant flow from OAuth 2.0. Once authenticated the browser will be issued with a Cookie - most likely using JWT so that we can sign it with a key for future verification.

The router should redirect requests to unauthorised resources to the login page for a list of URLS such as:

* `/function/system-dashboard` (authorisation required)

**Comment by alexellis** [comment]
I am making progress on this and will be posting an update soon.

**Comment by alexellis** [comment]
Related: https://github.com/openfaas/openfaas-cloud/issues/192

**Comment by martindekov** [comment]
Don't we use OAuth 2.0 for GitLab and GitHub now? If so is this closeable?

**Comment by alexellis** [comment]
Derek close: feature released
