### ISSUE TITLE
Deploy functions in Kubernetes Cant't contain {"Limits":{"Memory":"30Mi"}}

### ISSUE THREAD

**Issue by lmxia** [openfaas/openfaas-cloud#15]
I tried deploy functions  by the call of POST method system/functions:

request body:
```
{
	"Service":"lmxia-hello-python",
	"Image":"172.16.0.125:31115/lmxia/python-ci:latest-1b0af9f9c1166302e60c6ec4fe22b3ac89645c18",
	"Network":"func_functions",
	"Labels":{
		"Git-Cloud":"1",
		"Git-DeployTime":"2018-04-16",
		"Git-Owner":"lmxia",
		"Git-Repo":"faas-ci"
	},
	"Limits":{
		"Memory":"30Mi"
	}
}
```

502 status code get.
And succeed after removing

 	"Limits":{
		"Memory":"30Mi"
	}

**Comment by alexellis** [comment]
For Kubernetes you need to edit or replace https://github.com/openfaas/openfaas-cloud/blob/master/buildshiprun_limits_swarm.yml

Also I'm not sure there is any code that sets "30Mi" right now.. where did that come from?

**Comment by alexellis** [comment]
Default now set to run with a Kubernetes format, would be ideal if we could detect the orchestrator from the gateway endpoint and then pick a format. @viveksyngh can you do this? The gateway now gives the orchestrator name back.
