### ISSUE TITLE
Dashboard: incorrect links for usernames containing (-)

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#150]
## Expected Behaviour

For the following username we should present the correctly formatted endpoint link for his "hello-go" function.

https://system.o6s.io/overview?user=zhenfeng-zhu

i.e. https://zhenfeng-zhu.o6s.io/hello-go

## Current Behaviour

Due to some code in the dashboard UI calculating the "shortName" variable we are appending part of the username to the endpoint URL causing it to fail to work:

Instead of https://zhenfeng-zhu.o6s.io/hello-go we see: https://zhenfeng-zhu.o6s.io/zhu-hello-go

## Possible Solution

This should be a simple fix to the overview function's JavaScript and needs a dual-fix in the new PR via @kenfdev #148  

## Steps to Reproduce (for bugs)

1. Use links above or register a new GitHub username containing a dash.
2. Follow endpoint link.

## Context

This will affect people who have one or more dashes in their GitHub username.

Only the UI is affected from what I can tell and not the underlying router, deployment or meta-data.

**Comment by kenfdev** [comment]
Derek assign: me
