### ISSUE TITLE
Force scaling limits

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#154]
## Expected Behaviour

Scaling limits should be enforced as per the docs.

Let's have a min limit of 1 and max of 4

## Current Behaviour

Min = 1, Max = top upper bound

## Possible Solution

Update the buildshiprun command to give these labels/annotations.

**Comment by alexellis** [comment]
https://docs.openfaas.com/architecture/autoscaling/#minmax-replicas

**Comment by ivanayov** [comment]
Derek assign: me

**Comment by alexellis** [comment]
This is where the code creates labels for the deployment. Let's read the min/max values from the gateway_config.yml file.

https://github.com/openfaas/openfaas-cloud/blob/master/buildshiprun/handler.go#L156

Alex

**Comment by ivanayov** [comment]
Thanks. 
I just finished the code change and am going to test it
