### ISSUE TITLE
Function: Expose additional metrics

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#162]
## Expected Behaviour

We should be able to bubble up r/s for 2xx and non 2xx (error) codes over the last hour for use in the dashboard's detail page.

Without changing the gateway API we can query Prometheus directly for a single named function and bring back data.

Example query that returns the data with the codes (replace figlet in the string):
```
sum(rate(gateway_function_invocation_total{function_name="figlet"}[60m])) by (code)
```

The easiest way to do this may be to create a small function in Go which can query the data for a given function name and return the data in JSON for usage in the new dashboard in #148 

Request `/function/system-metrics/figlet`

The 60m can be hard-coded and implicit. 

Response

```
{
  "success": 1005,
  "failure": 50
}
```

Ideally we should think about average execution latency, but this is a stretch goal.

**Comment by viveksyngh** [comment]
we can also make time variable can be passed as input to the function.

**Comment by alexellis** [comment]
Since it's for the dashboard only and is not an API for general consumption let's keep it simple and get something ready. Later down the line we will need to think about whether this data goes into the gateway API.

**Comment by ivanayov** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Hi @ivanayov have you made any progress on this? I think it should be a reasonably quick task to prototype.

Alex

**Comment by bartsmykla** [comment]
Plan for this task:
- [ ] creating a function which will expose empty JSON
- [ ] parsing the function name from url
- [ ] getting metrics from prometheus
- [ ] updating JSON with the results from prometheus
- [ ] writing tests

Part 2:
- [ ] exposing that function as `/system-metrics/[function_name]`
- [ ] updating OpenFaaS Cloud dashboard
- [ ] updating the documentation

**Comment by alexellis** [comment]
Please add estimations for time for each part. Note updating the OpenFaaS Cloud dashboard is not part of this task. Feel free to raise a new issue for that.

**Comment by alexellis** [comment]
On "Get metrics from Prometheus" please give some analysis or 1-2 lines on how this will be done. I.e. look at the gateway code and decide if it can be re-used.

**Comment by bartsmykla** [comment]
@alexellis done :-)

**Comment by alexellis** [comment]
(I'm not seeing the feedback in the above.. done to which part?)

**Comment by ivanayov** [comment]
Tests to write:
- [ ] the function name is parsed properly (use async, non-async, system links, wrong url, gateway/[function name] - check which of these are use cases)
- [ ] the metrics are exposed properly ( ? can it be done in a unit test?)
- [ ] expected json results

- [ ] test for `/system-metrics`

**Comment by alexellis** [comment]
I'll just repeat this a second time.

There is no endpoint " test for /system-metrics" in this task. The function may be deployed as:

`/function/system-metrics` and should be part of the stack.yml for OpenFaaS Cloud.

The name of the handler folder will be metrics but the `system-` prefix means we can expose it via the router as `https://system.domain.com/metrics`. Please do not confuse this with the `/system/` routes which belong to the API Gateway only.

**Comment by ivanayov** [comment]
We're done with exposing the metrics and returning them as a JSON. What's left is to trigger the prometheus host/port and write tests.

**Comment by ivanayov** [comment]
Everything except Part 2 (which we discussed may drop from this issue) is now done.
For more details, please review the pull request

**Comment by alexellis** [comment]
Merged, released. Thank you both.
