### ISSUE TITLE
Move CUSTOMERS validation out of github-push

### ISSUE THREAD

**Issue by martindekov** [openfaas/openfaas-cloud#163]
Soon we would like to move out of `github-push` for event handling and support more than push events from github and give that to `github-event`. Currently the CUSTOMER validation is handled in `github-push`

## Expected Behaviour

Should extend the `PushEvent` struct with `sender` field to compare by that since the field is present in the outer layer of `X-GitHub-Event: push`,`X-GitHub-Event: installation_repositories` and `X-GitHub-Event: integration_installation_repositories`.

## Current Behaviour

We handle the situation in `github-push` by struct which is unique to the push event.

## Possible Solution

Move the CUSTOMERS handle out of github-push into github-event and create separate struct or extend existing struct which handles events so it can compare by `event.Sender.Owner` rather than more specific `event.PushEventRepository.Owner.Login` since every event contains
```
...
    "sender": {
        "login": "martindekov",
...
```

## Steps to Reproduce (for bugs)

N.A. 

## Context

If we want the `github-event` function to handle the redirection we cant contain CUSTOMERS validation in `github-push`

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

18.06.0-ce

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

Docker Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):

Ubuntu 18.04

* Link to your project or a code example to reproduce issue:

N.A.

**Comment by martindekov** [comment]
I can work on that when we settle on solution

**Comment by alexellis** [comment]
Sounds fine to me, but we have to switch over to github-event first and github-push must validate only with the internal trust signature.

**Comment by alexellis** [comment]
@martindekov you can work on this now that I've merged the work to switch to github-event as the primary endpoint.

**Comment by martindekov** [comment]
Ok I am on it

**Comment by martindekov** [comment]
Derek assign: me
