### ISSUE TITLE
Build dashboard static assets using a Node.js container

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#169]
## Expected Behaviour

`make` within the dashboard sub-folder should generate static assets using a container and a bind-mount so that we have a consistent experience for all developers.

## Current Behaviour

Depends on local tooling such as `yarn` which may be at different versions.

## Possible Solution

Use the official Node.js / Alpine container to carry out the build by mounting the source/destination folders. This may need a Dockerfile or may be possible with a simple `docker run`.

## Steps to Reproduce (for bugs)

1. `cd dashboard`
2. `make`

This should work without `yarn` or `node` on the local system.

**Comment by jkrol2** [comment]
@alexellis  Can I work on it?

**Comment by ivanayov** [comment]
@jkrol2 feel free to take it :)

**Comment by alexellis** [comment]
Hey @jkrol2 do we have you on Slack yet? Would you like to join in the discussion in the #ui-taskforce?

Alex
