### ISSUE TITLE
Proposal: Automate the UI build

### ISSUE THREAD

**Issue by kenfdev** [openfaas/openfaas-cloud#174]
## Expected Behaviour

Push a new UI client JavaScript code and the container image gets built with the newest assets. This means the final bundled assets doesn't need to be managed with git and the developer doesn't need to commit it either.

## Current Behaviour

You need to hit `make` or build the assets with something like `yarn build` before committing. Which tend to be forgotten. Also, while the code under `client` is able to be merged, the bundled assets inside the `dist` directory will always have a merge conflict because it is minified to 1 line of code.

## Possible Solution

Perhaps a new template for SPA functions which have multiple stage docker builds. One to bundle the assets and the other for the final container image.

## Context

I myself frequently forget to hit `make` to create the bundles. This is just a matter of pushing the bundles with a new commit but having to always resolve conflicts because of other's code getting merged first will not be a good experience.

Things I've tried:

**Use npm scripts and `preinstall` to build the assets when the function gets built**

An error occurs when trying to `cd client` which says `cannot run in wd %s %s (wd=%s) `. This is a permission problem which happens in `npm install` with `root`. [related issue](https://github.com/nodejs/docker-node/issues/474)

I've edited the template [here](https://github.com/openfaas-incubator/node8-express-template/blob/master/template/node8-express/Dockerfile#L33) to use the `app` user which solves the problem above.  But another problem is that the original code under `client` remains inside the final container (which makes it HUGE). Hence, we'll need a multi-stage build to solve the latter problem.

**Comment by kenfdev** [comment]
Derek add label: proposal

**Comment by bishwenduk029** [comment]
@kenfdev , can we also add as an additional measure, git postcommit hook via Husky to allow for make/"yarn run build" to be executed every time a commit is made in local git.

**Comment by alexellis** [comment]
We don't really want to have multiple people generating the dist folder. Ideally we could do but will have clashes on PRs. We could use a local dist folder in the git ignore for local development and then have the Docker image build or Makefile produce the final image with the generated contents via CI.

**Comment by alexellis** [comment]
Derek add label: design/review

**Comment by Waterdrips** [comment]
`dist` folder is in gitignore, it is generated from the code and shouldnt live in the repo. Make is used to generate it, and its bundled into the node container as part of faas-cli up. 

This is a good way of working, we might want to create a `make deploy` command instead that just runs `make build` and then `faas-cli up`
