### ISSUE TITLE
Mange DNS suffix in one place for internal services

### ISSUE THREAD

**Issue by bartsmykla** [openfaas/openfaas-cloud#186]
Because for kubernetes hostnames need to contain namespace (if you want to call them from other namespace) and for docker swarm we don't. Sometimes we need "gateway.openfaas" (K8s) and other times "gateway" (swarm). That's configured in each URL via `github_config.yml` maybe it's a good idea to improve that experience.

## Expected Behaviour
Have one place where we can specify for example `dns_suffix` which will be added to hostnames. So instead of manually changing all hostnames, we could set it in one place and it'll be automatically added to hostnames.

## Current Behaviour
We need to manually make a change in all affected places.

## Possible Solution
Creating `dns_suffix` and then appending it to all hostnames

## Context

Alex Ellis: When deploying onto Swarm all the links have to be changed and missing one can result in an obscure error - the same is true of a custom namespace on Kubernetes.

**Comment by martindekov** [comment]
Derek assign: me

**Comment by martindekov** [comment]
Since we get the gateway in almost every function in the cloud is it a good idea to create function that formats the gateway in SDK and re-vendor rather than appending it to all the handlers ?

**Comment by alexellis** [comment]
What would you suggest? I see you raised #211 ?

**Comment by martindekov** [comment]
I already made the change in #206 I only need to fix/Re-open the PR since there have been many re-vendoring of the sdk which may result in that 3200 files that have been changed.Also I need to check if `../gateway_config.yml` syntax works for dashboard if needed file is one directory up to apply the change not only for the gateway of the main functions but for dashboard.

**Comment by bartsmykla** [comment]
Closing issue, because of it's age. Feel free to recreate it.

**Comment by alexellis** [comment]
Derek open

**Comment by alexellis** [comment]
Hi Bart, appreciate that you're no longer active and some of your PRs may not get finished, but I would appreciate it if you could ask before closing issues across the project. Thanks, Alex
