### ISSUE TITLE
UI: Dashboard - set progress bar to green for 1/1 replicas, not red

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#188]
## Expected Behaviour

The dashboard should show "ok" / green for 1/1 replicas.

## Current Behaviour

100% of max replicas i.e. 1/1 shows as red which is not a positive sign to the user.

1/1 is shown when that is the actual limit or the limit is unknown.

## Possible Solution

Suggest / make a fix or adjustment to the React code in dashboard/client/

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by viveksyngh** [comment]
Derek add label: area/dashboard

**Comment by viveksyngh** [comment]
Derek add label: skill/beginner
