### ISSUE TITLE
UI Dashboard: change endpoint link to "copy to clipboard"

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#190]
This change is for the Overview page of the dashboard.

## Expected Behaviour

The endpoint link may not be useful for many people to visit from the dashboard, so let's change the current behaviour of the link to "copy to clipboard" then add another link by it with the icon to show "open in new window"

https://fontawesome.com/icons/link?style=solid

https://fontawesome.com/icons/external-link-alt?style=solid

Suggestion: from Allen / Pato.

## Current Behaviour

The endpoint link will open the endpoint and "copy" is done by right-clicking and clicking "Copy link location"

Update dashboard/client, run `make` locally but do not commit the `dist` folder.

**Comment by kenfdev** [comment]
Derek add label: area/dashboard

**Comment by kenfdev** [comment]
FYI, the gateway UI implements it like this:

https://github.com/openfaas/faas/blob/master/gateway/assets/script/bootstrap.js#L26

Care is needed for browsers who support `document.queryCommandSupported('copy')`

**Comment by kenfdev** [comment]
Derek add label: skill/beginner

**Comment by alexellis** [comment]
Good comments Ken. This should be a quick PR for someone to pick up.

**Comment by bartsmykla** [comment]
Derek assign: me

**Comment by bartsmykla** [comment]
Estimate: 30 minut

**Comment by bartsmykla** [comment]
![image](https://user-images.githubusercontent.com/11655498/45829323-9607c800-bcf2-11e8-8cc8-67a2661fd651.png)

**Comment by alexellis** [comment]
Hi Bart, what is the image for?

This task is for the overview page (it may also apply to the details page) 

Alex

**Comment by jaigouk** [comment]
@alexellis @bartsmykla 
I added `react-copy-to-clipboard` and the commit was not merged. so I am thinking about creating a new PR for the behaviour and then I found this ticket. 

![copy-badge-md](https://user-images.githubusercontent.com/6720/45879356-792bcd00-bda4-11e8-97c3-dbca5cddac7f.gif)

**Comment by martindekov** [comment]
Derek close: we no longer support overview page and saw @bartsmykla tried to close this in a PR
