### ISSUE TITLE
UI Dashboard: Endpoint truncated to "Endpoi..."

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#191]
## Expected Behaviour

"Endpoint" should show the full word, but doesn't

The icon for "Invocations" should not wrap onto a new line either - it looks a bit messy.

## Current Behaviour

The word "Endpoint" is is truncated to "Endpoi..."

## Possible Solution

I think we should change this to "Link:" but also implement the icons from #190 

![wrapping](https://user-images.githubusercontent.com/6358735/45709463-05a77700-bb7c-11e8-8f24-87466d618a12.png)

**Comment by alexellis** [comment]
Derek add label: area/dashboard

**Comment by bartsmykla** [comment]
Derek assign: me
