### ISSUE TITLE
Experiment: create an org and install OpenFaaS Cloud on a repo

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#192]
## Expected Behaviour

OpenFaaS Cloud should be able to build/deploy repos that belong to an organisation.

## Current Behaviour

I don't know if that is supported.

## Possible Solution

Try this out and report back findings with suggestions on changes needed.

## Steps to Reproduce (for bugs)

1. Create a GitHub org on the free plan
2. Create a repo under the org with a valid function and `git push`
2. Install your GitHub App onto the org's repo
3. Push code and see what happens

## Context

This is a very useful use-case for collaboration where teams may be using an organisation for their functions rather than an individual user-account.

**Comment by s8sg** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Derek unassign: s8sg

**Comment by alexellis** [comment]
@s8sg let me know on Slack he can't take this task now.

**Comment by viveksyngh** [comment]
Derek assign: me

**Comment by viveksyngh** [comment]
It's is working fine for an organization as well. I have deployed https://github.com/faas-furious/of-cloud-test-fn repo to OpenFaaS cloud. 

http://142.93.39.213:8080/function/system-dashboard/faas-furious/

**Comment by alexellis** [comment]
I'm seeing missing data on the dashboard?

**Comment by viveksyngh** [comment]
It was due to the mismatch in the version of the dashboard and other functions. I have updated the it please check it now.
