### ISSUE TITLE
Functions cannot be deployed on Kubernetes

### ISSUE THREAD

**Issue by kvuchkov** [openfaas/openfaas-cloud#193]
Functions cannot be deployed on Kubernetes due to the new memory limit mechanism.

## Expected Behaviour
Functions on k8s to be deployed successfully with limit suffix Mi.

## Current Behaviour
Function pods remain in CreateContainerError state b/c function deployments have a memory limit with suffix of "m" instead of "Mi".

## Possible Solution
The buildship run function was updated, but the docker image reference remains the same, i.e.  in master, the image in stack.yml is not referencing an image build from the code in master.

The version of the image needs to be increased to 0.8.0 since this is new behaviour and is changing the existing behaviour, i.e. is not a maintenance change.

## Steps to Reproduce (for bugs)
1. Deploy latest OpenFaas-Cloud on k8s
2. Deploy any function via Github

## Your Environment
Kubernetes v1.10.3

**Comment by alexellis** [comment]
Thank you for raising the issue. Can you raise a PR for the updated version in the YAML file? I'll do a build/push before merging. Let's also increase the default from 20 to 128.
