### ISSUE TITLE
Provide feedback via outgoing webhook

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#2]
An outgoing webhook URL configured via environmental variable should allow for events to be posted to a remote server for status.

* Whenever a GH-push is received
* Whenever buildshiprun executes
* Whenever of-builder pushes a new image successfully or if it fails and how long it took

The payload format should be in JSON and include context:

i.e.

```json
{
 "owner": "alexellis",
 "repo": "kubecon-tester",
 "source": "gh-push"
}
```

The URL to receive web hooks should be set the stack.yml file - probably in the same file that has the gateway configuration URL.

A specific event would extend the JSON above with specific information like a "message" field:

```json
{
 "owner": "alexellis",
 "repo": "kubecon-tester",
 "source": "gh-push",
 "message": "owner not in CUSTOMERS file"
}
```

We may also want some additional fields to represent whether this is a success / warning message such as in the example above.

Since all OpenFaaS functions are written in Go we should have a common package with the struct representing the JSON event and a HTTP client/wrapper for easy auditing of events.

**Comment by ericstoekl** [comment]
Derek assign: me

**Comment by alexellis** [comment]
@ericstoekl did you see the changes that went up?

**Comment by ericstoekl** [comment]
Haven't had time yet due to the faas-cli work, but I'll find some cycles to work on it today.

**Comment by ericstoekl** [comment]
Now that the `sdk.PostAudit` function is in the SDK, the real issue here is figuring out what we want the audit-event to go to. I have been using `webhookstash` for testing, but we should have a database for this. Maybe we deploy minio with the of-cloud? Maybe we just use a simple database like sqllite for now?

**Comment by alexellis** [comment]
Derek: close

**Comment by alexellis** [comment]
It should be posted to HTTP and at that point it's agnostic as to whether you want to store that in a DB via a function, in a Git log, Kafka transaction log or a Slack channel.
