### ISSUE TITLE
Update router to prevent access to `/` path

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#209]
## Expected Behaviour

The root path should not be available via the router:

https://system.domain.com/

or

https://alexellis.domain.com/

## Current Behaviour

Router hosts are translated to function paths i.e. /function/alexellis-PATH or /function/system-PATH

## Possible Solution

Update the router to check for the Path - if it is "" or "/" then return 404 not found.

## Steps to Reproduce (for bugs)

1. Run the router via `docker run` or deploy with OpenFaaS Cloud setting upstream_url to a valid gateway
2. Add an /etc/hosts file entry to the IP where you are running the router or use `-H "Host: name.."
3. See the request as above

## Checklist

- [ ] Reproduce issue in unit test
- [ ] Add unit tests for positive / negative cases
- [ ] Fix issue and demonstrate console output on this issue / the PR

https://github.com/openfaas/openfaas-cloud/tree/master/router

**Comment by rgee0** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Derek close: something about people using keywords @rgee0 ? :smile:

**Comment by alexellis** [comment]
Fixed via #212 (thank you very much Richard :+1: :100: )
