### ISSUE TITLE
UI Dashboard: Should provide ability to logout/deauthenticate when OAuth merged

### ISSUE THREAD

**Issue by johnmccabe** [openfaas/openfaas-cloud#213]
## Expected Behaviour
When the OAuth feature is merged it should be possible to logout/deauthenticate from the service.

## Current Behaviour

Current OAuth implementation doesn't include the ability to logout/deauthenticate.

## Possible Solution

Add a logout option which deletes the auth cookie and redirects to the standard landing page. Note its probably worth tweaking the design slightly to accomodate this, adding the logged in user to the right of the top navbar with logout as a dropdown option.

**Comment by burtonr** [comment]
@johnmccabe I think this can be closed as the "ability to logout" is available as indicated by the PR to add a logout button is here: #295
