### ISSUE TITLE
Proposal UI: Use a Bootstrap library vs HTML

### ISSUE THREAD

**Issue by bartsmykla** [openfaas/openfaas-cloud#214]
In our roadmap there is plan moving from native HTML/JSX components with bootstrap classes to bootstrap components using libraries like `react-bootstrap` or `reactstrap`.

I want to pick up this task and I'm thinking about usage of `reactstrap` because of bootstrap 4 (react-bootstrap is not supporting bootstrap 4), which is currently maintained, and I think more future proof and easier to work with framework.

@jaigouk @kenfdev you've spend a lot of time and afford on our UI already and you did great job. What do you think about that?

Let's make some discussion about it.

## Expected Behaviour
Have a set of bootstrap component which will make improvement of UI easier and faster.

## Current Behaviour
If we want to use some part of bootstrap, we need to create whole component by hand using bootstrap's classes.

## Possible Solution
UI refactoring using `react-bootstrap` or `reactstrap`

## Context
I think that using one of libraries with bootstrap components will make creating new features or/and UI changes easier and faster.

**Comment by bartsmykla** [comment]
Derek add label: area/dashboard

**Comment by bartsmykla** [comment]
Derek assign: me

**Comment by jaigouk** [comment]
for `react-bootstrap`, they have a doc for using v4

https://react-bootstrap.netlify.com/migrating

**Comment by bartsmykla** [comment]
@jaigouk what do you think about an idea of moving to bootstrap 4?

**Comment by kenfdev** [comment]
Thanks for the issue Bart!  Yes, trying to add features which use jQuery is pretty much a pain unless we use those frameworks. I wanted input about whether to use `react-bootstrap` or `reactstrap`, too. As @jaigouk points out, they're (react-bootstrap) in beta for bootstrap 4. I don't have enough time to research the pros and cons of the two (looks like reactstrap has been focusing on v4 for a longer time maybe?).
Jag had some concerns about using the full library. Would like his input here, too.

Since we haven't heavily used the library yet, either one could be a choice.

**Comment by bartsmykla** [comment]
Do you have anything against idea, to play with it by me (I think that I'll start with `reacstrap` because I prefer working with it, and if there will be anything wrong, I'll try `react-bootstrap`). We could discuss on living PR.

**Comment by alexellis** [comment]
@bartsmykla please write-up the pros and cons for us including whether you've encountered any issues with our current implementation using Bootstrap 3.

**Comment by alexellis** [comment]
> Jag had some concerns about using the full library. Would like his input here, too.

Hey @jagreehal it'd be great if you could provide some input on this thread?

**Comment by bartsmykla** [comment]
My thoughts about bootstrap 3/4:
- bootstrap 4 uses flexbox natively, which makes creating new features much easier without need of making ugly hacks if you want to vertically center anythinig
- you can easily decide if you want to use components with jquery or not
- native utility classes - right now you can do almost anything without use of external styles or with small amount of them:
    - auto margins
    - new spacing utilities
    - vertical centering
    - responsive sizing and floats
- bootstrap 4 uses rems instead of pixels as a primary css unit, which makes easier to change more general parts of a design (let’s say we want to increase font size)
- If we decide that we wanna switch to using some style preprocessors, SASS is much more popular and it’s first choice of most of new projects, bootstrap 4 switched to SAAS, and we could use that even improve styling more by removing almost entire need of using custom styling 

With bootstrap 3 I faced a lot of problems with spacing (margins and paddings) which were resolved by adding custom styles, which makes them harder to maintain if you wish to have mobile first design, currently if something is not folding correctly, there are native classes to help with it, and by using them we can be sure that we are not breaking anything.

From the opposite site, the only const which I can think of is not supporting IE8-9 by bootstrap 4.

**Comment by bartsmykla** [comment]
@kenfdev @jaigouk @jareehal I spent some time on that. I used reactstrap, and that's the result: https://gateway.dedal.io/function/system-dashboard/bartsmykla/ give me your thoughts, and if everything is ok, I can create Pull Request and we can work on that, if not, we can decide which direction we wanna take. I'm open to any suggestion and critique. :-)

**Comment by jaigouk** [comment]
It looks good to me. i just pushed `react-bootstrap` to move forward with modal part. I saw @bartsmykla worked on most of the details to compatible with `reacstrap`. thanks for the hard work.

**Comment by jagreehal** [comment]
I've just done a couple of prototypes this evening using reactstrap.  Looks good to me and hopefully reduces the need for jQuery and popper.js. @bartsmykla did you include it in the project using the npm module?

**Comment by kenfdev** [comment]
Your thoughts about 3 -> 4 are very nice and I can't agree more. Could we  have a peak with your code? Just curious how it looks like.

**Comment by alexellis** [comment]
@bartsmykla @jagreehal @jaigouk how is the PR looking now? What do we want to do?

**Comment by bartsmykla** [comment]
I think that it looks good. @jagreehal @jaigouk what do you think?

**Comment by jaigouk** [comment]
I am fine if we're going to stick with bootstrap. my colleague told me to take a look at https://bulma.io/

**Comment by alexellis** [comment]
Looks like we have consensus on the proposal. @bartsmykla please can you rebase your PR and look at the feedback from the community on the thread?

**Comment by bartsmykla** [comment]
@alexellis rebased. :-)
