### ISSUE TITLE
git-tar - cache templates

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#215]
## Expected Behaviour

Given that templates rarely change, we should cache the 3-4 template repos we pull in from GitHub and copy them to the working directory for the shrink-wrap stage

## Current Behaviour

We clone all 3-4 repos for every function in the stack file on every `git push`. It's not necessary. I think we could cache to a known-folder in `/tmp/` and copy the files in from there.

**Comment by martindekov** [comment]
Derek assign: me

**Comment by martindekov** [comment]
Not sure should we be moving this PR/Issue along, we had discussions with Lucas in the PR whether or not this brings true value in case the function is scaled.
