### ISSUE TITLE
Experiment: can we build buildkit for armhf?

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#216]
## Expected Behaviour

It would be amazing to run OpenFaaS Cloud on a Raspberry Pi cluster.

## Current Behaviour

Current blocker as I see it is having a Docker image available for BuildKit.

## Possible Solution

Research building BuildKit for armhf

**Comment by alexellis** [comment]
cc @rdimitrov

**Comment by zeerorg** [comment]
Would like to help on this issue.
