### ISSUE TITLE
Research: what would it take to use Kaniko vs. BuildKit?

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#217]
## Expected Behaviour

Could OpenFaaS Cloud use Kaniko as an alternative to BuildKit?

Kaniko is Google's alternative container-builder, it is slower and does not have caching but uses a slightly different security model which could be useful. See also #216 perhaps Kaniko would build for armhf if BuildKit cannot.

## Current Behaviour

BuildKit is used as a re-useable daemon, but Kaniko uses a sacrificial Docker container - once a single build has been done the container is unusable for anything else.

I built OpenFaaS images using the `faas-cli` to complete all the steps and a Kubernetes Job, but if we implement this for OpenFaaS Cloud we should not couple ourselves to Kubernetes only since we have other back-ends to support.

https://blog.alexellis.io/quick-look-at-google-kaniko/

**Comment by alexellis** [comment]
Thanks

Do you want to try to see if Google will accept it as an upstream PR?

Alex

**Comment by rdimitrov** [comment]
That's a great idea actually. But for the time being, I think both Amazon and Google don't have ARM support for their credential binaries, so it might not be useful to prepare something yet.
