### ISSUE TITLE
Update status/checks API for when using an invalid template

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#219]
## Expected Behaviour

If someone tries to build with a template which is unavailable in the repos we clone i.e. `php` then they should receive feedback on that.

We also need to block `dockerfile` temporarily and give feedback to the user.

## Current Behaviour

@stefanprodan tried to use `dockerfile` and received no or poor quality feedback. It was confusing.

**Comment by martindekov** [comment]
Should this be closed? Now we have support for custom templates

**Comment by martindekov** [comment]
Will reference this along with #417

**Comment by alexellis** [comment]
The remaining piece is:

> then they should receive feedback on that.

**Comment by martindekov** [comment]
I will add the bad check along with the code which will validate the downloaded templates 👍

**Comment by martindekov** [comment]
Derek close:I will close this as there is existing Issue about the exact same thing
