### ISSUE TITLE
functions doesn't honour gateway_url value provided by env

### ISSUE THREAD

**Issue by s8sg** [openfaas/openfaas-cloud#22]
environment file `gateway_config.yml` is being provided with configurable `gateway_url`. Although in many Functions the `gateway_url` value from ENV is not being used instead it has been hardcoded. It eventually fails the function call when deployed manually with different url

**Comment by alexellis** [comment]
I'm not sure that's true of the latest version. Can you check again as I pushed changes yesterday.

**Comment by s8sg** [comment]
Ahh forgot to sync my fork. Thanks! Closing
