### ISSUE TITLE
Research: SealedSecrets with Docker Swarm

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#220]
## Expected Behaviour

Can we use the SealedSecrets code to un-seal secrets, create them and then attach them to functions on Docker Swarm?

## Current Behaviour

This feature is unavailable for OpenFaaS Cloud when running with Docker Swarm

## Possible Solution

The OpenFaaS API may gain the ability to create secrets, but for now it does not have that capability. 

This research task does not need to have an end-to-end demo to show it's feasibility. I'd just like to see an approach outlined and some initial work to show a secret Sealed with the CLI being unsealed at runtime in order to be attached to a function. The result may be a unit test, some snippets of code or a Gist. It might even be "this cannot be done" - but I suspect that it can be done.

**Comment by alexellis** [comment]
Derek add label: Hacktoberfest

**Comment by alexellis** [comment]
cc @zeerorg

**Comment by alexellis** [comment]
My hypothesis is that that we could pick apart which structs are used by SealedSecrets from the Kubernetes client API and make use of them to import secrets in Swarm or other back-ends.

This would help level the secrets experience for users on Swarm, and we should be able to leverage the new secrets API in OpenFaaS for the `CLUD` of secrets keys and values.

**Comment by zeerorg** [comment]
I was thinking of how we could keep it compatible with existing OpenFaas' cloud secret workflow.

**Comment by alexellis** [comment]
By creating a function named import-secrets-swarm I would think. First things first let's prove it can even be done without sending patches upstream to Bitnami.

**Comment by zeerorg** [comment]
I think we can skip using SealedSecrets altogether if we are supporting swarm. The imports-secrets-swarm function can be based on what of-git-tar does but with secrets, by using OpenFaas' api calls.

**Comment by zeerorg** [comment]
Figuring out the semantics of encryption and decryption would be hard, and also we would need to generate public and private keys.

**Comment by alexellis** [comment]
> Figuring out the semantics of encryption and decryption would be hard, and also we would need to generate public and private keys.

There is no need to do this, the code is already written by Bitnami, we just have to unpick it from the Kubernetes client-set / go-client.
