### ISSUE TITLE
Feature: OAuth 2.0 login via GitLab

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#223]
## Expected Behaviour

When installed on-premise or on a private cloud GitLab provides the ability to create an OAuth 2.0 App. This can be used for login in the same way that we're doing with GitHub via #197 

This would mean users such as VMware or Vision Banco could set up their own internal / private OpenFaaS Cloud completely on-premise with Kubernetes and GitLab.

## Current Behaviour

Initial work for login with GitHub will be merged shortly via #197 and we have a working PR showing the CI/CD component of GitLab via #101 

## Possible Solution

An installation will only be connected to one source-control management system at a time - either GitHub or GitLab, in the future @kvuchkov may help add support for BitBucket.

In this task we should provide the ability to do the following:

* Opt to use GitHub or GitLab via one-time configuration
* Provide login via a GitHub or GitLab App
* Capture and store JWT claims in the same name / format depending on whichever is the system of record

For research and testing set up your own GitLab server on a public cloud. Limited access can also be given to https://gitlab.team-serverless.xyz/ upon request.

**Comment by martindekov** [comment]
Derek close: I believe this was already implemented in #280
