### ISSUE TITLE
Research item: Automate initial setup with Ansible

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#226]
## Expected Behaviour

It would make it easier to setup/deploy if we could automate some of the steps such as secret creation etc. Some initial fact gathering is required, but after that we could possibly automate some of the process in a similar way to how @rgee0 did it with https://www.openfaas.com/blog/deploy-digitalocean-ansible/

This is not on the critical path, but @rgee0 offered to look into it. Would also be good to get other suggestions/ideas on automating or stream-lining the initial Day 0 setup.

Alex

**Comment by martindekov** [comment]
Derek close: I believe we solved the initial setup with ofc-bootstrap?
