### ISSUE TITLE
git-tar: Add custom template configuration

### ISSUE THREAD

**Issue by martindekov** [openfaas/openfaas-cloud#229]
Currently If we want to add our own custom template we need to enter git-tar, find the place we load the templates and add the string to our repository containing our template so the template can be downloaded.

## Expected Behaviour

Have environmental variable in some `.yml` file in which we add the github repository containing our custom repo

## Current Behaviour

To add custom template we need to enter in the code and add manually the URL of the repository with our template.

## Possible Solution

Add configurable environmental variable in which people can add their repositories with templates and modify `git-tar` to use that variable.

## Steps to Reproduce (for bugs)

N.A. This would be a feature

## Context

People in slack have been asking how to add their own template, and there is no way to do it through configuration.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
-
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux
* Link to your project or a code example to reproduce issue:
N.A.
* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
cc @johnmccabe (re: PHP conference)

**Comment by martindekov** [comment]
Since I already have opened PR #250 I can quickly do this one if @johnmccabe didn't start working on it?

**Comment by martindekov** [comment]
Derek assign: me

**Comment by martindekov** [comment]
My approach would be `custom_templates: "https://github.com/openfaas-incubator/node8-express-template.git,https://github.com/openfaas-incubator/golang-http-template.git"` other way would be to create `custom_template.yml` file copy it in the container then parse the yml like we would do with build options in faas-cli. If there are no other suggestions, which approach sounds better ? @openfaas/faas-team
