### ISSUE TITLE
GitHub OAuth 2.0 - store org membership in claims

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#234]
## Expected Behaviour

The dashboard should be able to display functions belonging to any orgs you belong to such as `openfaas` which has a linked repo "cloud-functions". I belong to the org (as do some of you) so I should see those functions on my dashboard.

## Current Behaviour

I have to visit the dashboard separately

## Possible Solution

1. When collecting the user's profile from GitHub via after getting an access_token we should also fetch the org memberships and store those as a claim.
2. Use these claims in the dashboard (when present) to make a series of calls to system-list-functions to get a full list of functions to display

**Comment by alexellis** [comment]
API to invoke "List user organizations": https://developer.github.com/v3/orgs/#list-user-organizations

**Comment by alexellis** [comment]
@martindekov please also look into the GitLab API to find the equivalent to "organizations" and equivalent API to call.

**Comment by alexellis** [comment]
This file stores claims right now, so it needs extending to store a comma separated list of organisations. https://github.com/openfaas/openfaas-cloud/blob/master/auth/handlers/oauth2.go

**Comment by martindekov** [comment]
Derek assign: me

**Comment by martindekov** [comment]
I made the change but before that one question. Should I extend the `OpenFaaSCloudClaims` to have `[]orgs` field or you want me to add it literally as a comma separated list in single string?

**Comment by alexellis** [comment]
You could add a utility method perhaps? The claims are generally flat I believe.

**Comment by martindekov** [comment]
I just extended the struct `OpenFaaSCloudClaims` with `Organizations` field and added the value there and opened ^ PR. If this is not the right approach I can add the utility method but not sure where should I return/amend the organizations in that case

**Comment by alexellis** [comment]
Utility method could be: `[]string GetOrganizations()` which parses the internal field and returns the values. Attached to the `OpenFaaSCloudClaims` struct.

**Comment by martindekov** [comment]
Aaah ok now I get it but will look into where I should use it cause I am not very familiar with the code.

**Comment by alexellis** [comment]
It would be consumed by the dashboard, so you could add it but it's not strictly necessary.

**Comment by martindekov** [comment]
I think we should continue the discussion here not in the PR since it is not for gitlab. The organizations in GitLab are called groups. You create group chose private/internal/public much like github then add members to it like maintainers. I think this is what we are looking for https://docs.gitlab.com/ee/user/group/

**Comment by alexellis** [comment]
Would that translate to the way we are storing org claims in your PR? I.e. could you store the GitLab info in the same way?

**Comment by martindekov** [comment]
In github we get user and the organizations that the user is in are displayed. GitLab does not give that info on the User part, but the other way around -> in case you know the group/id you list the users. I checked API  here https://docs.gitlab.com/ee/api/users.html for users reference and for groups(organizations) here https://docs.gitlab.com/ee/api/groups.html#group-members

**Comment by alexellis** [comment]
Are you also searching Google for info? I found this -> https://gitlab.com/gitlab-org/gitlab-ce/issues/34230 - looks like there may be a way to see groups per user?

**Comment by alexellis** [comment]
Related - https://gitlab.com/gitlab-org/gitlab-ce/issues/48165

**Comment by alexellis** [comment]
Looks like GitLab allows you to query a user by using the `Sudo` header such as:

```
curl -H "Sudo: martindekov" --header "PRIVATE-TOKEN: $PRIVATE_TOKEN" "https://gitlab.domain/api/v4/groups"
```

**Comment by martindekov** [comment]
I forgot to close this issue.. Should I ? The organizations are stored now in claims for GitHub? The GitLab organization is not though..
