### ISSUE TITLE
UI: Dashboard - introduce blank slate feature

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#236]
## Expected Behaviour

When you land on the page there should be a link or action button clearly displayed when you have no functions. This is the blank slate / state for the dashboard. See the regular OpenFaaS UI portal for an example.

## Current Behaviour

We see a vague error message like "No functions", but probably don't need the grid rendered at all. There is no clear next-action for the user to take and we can improve that.

![blank-slate](https://user-images.githubusercontent.com/6358735/46096974-8687f380-c1b8-11e8-9a9d-d5f05ef55f5e.png)

## Possible Solution

We should make some suggestions / designs of how we can improve this. Allen cc @allendjal could probably help here.

**Comment by allendjal** [comment]
Proposed mockup attached here. Includes CTAs: create a new function + learn about openfaas functions
![functions-blank-slate](https://user-images.githubusercontent.com/38286758/46130827-16e12b00-c1ef-11e8-8d86-a2e8f57620b0.jpg)

**Comment by alexellis** [comment]
@bartsmykla how many hours do you think this task would take you to complete?

Thanks,

Alex

**Comment by bartsmykla** [comment]
4h

**Comment by Waterdrips** [comment]
Derek assign: me
