### ISSUE TITLE
Optimization for github-push

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#245]
## Expected Behaviour

From @ivanayov - we can optimize github-push by checking GitHub's RAW CDN for a stack.yml file before going ahead and cloning a repo.

The RAW CDN will give a 404 error which would save us on bandwidth:

* Existing file:

https://raw.githubusercontent.com/alexellis/not-fn/20377d9cb111bd71cc246bac4dfe38aee89cb7a2/README.md

* File not found:

https://raw.githubusercontent.com/alexellis/not-fn/20377d9cb111bd71cc246bac4dfe38aee89cb7a2/stack.yml

## Current Behaviour

We clone first, then check - then give a status message. Example: https://github.com/alexellis/not-fn/runs/20222663

This is wasteful and inefficient - some people install the GitHub App on every repo (anything they have as a fork or project will be cloned 😞 )

## Code

We should add the check here:

https://github.com/openfaas/openfaas-cloud/blob/master/git-tar/function/handler.go#L57

**Comment by alexellis** [comment]
Fixed via: https://github.com/openfaas/openfaas-cloud/commit/aa5828702f0e82f5b1070cb1c1b73ff908ceb4e3

cc @ivanayov

Martin @martindekov you'll probably need to make sure you ignore this code when running in GitLab or find the alternative

**Comment by alexellis** [comment]
Derek close: released

**Comment by martindekov** [comment]
This is optimization with git-tar so I think if we abstract away
```
addr := fmt.Sprintf("https://raw.githubusercontent.com/%s/%s/master/stack.yml", repo.Owner.Login, repo.Name)
```
and maybe format it by field (check CloneURL containing gitlab,github?) we won't have to worry duplicating the change for both push functions. I can create Issue and add the format function.
