### ISSUE TITLE
github-push - create an invalid status/check when building non-master

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#246]
## Expected Behaviour

We should update the status / checks API when building from non-master, since there is currently no feedback given.

## Current Behaviour

We create an audit message but don't provide feedback to the user via checks API / status.

```
[github-push] alexellis/not-fn: 'refusing to build non-master branch: refs/heads/faas-team'
```

## Steps to Reproduce (for bugs)

1. Add GitHub App to new repo
2. In a new branch add stack.yml and functions
3. Do a push

**Comment by ivanayov** [comment]
@kvuchkov are you working on it or it's free to work on?
