### ISSUE TITLE
Audit size of function build context

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#247]
## Expected Behaviour

In the audit log I'd like to see the size in bytes (i.e. KB or MB) whichever applies of each build context that we pass as a tar.

Functions: either `git-tar`, `buildshiprun` where we create or process the tar?

## Current Behaviour

No observability for the OFC operator.

Suggestion via @kvuchkov

**Comment by viveksyngh** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Derek close: implemented by @alexellis
