### ISSUE TITLE
git-tar should invoke deploy (buildshiprun) in parallel

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#252]
## Expected Behaviour

git-tar should invoke deploy (buildshiprun) in parallel

## Current Behaviour

If a stack has 10 functions they are built in serial one at a time. Use an errgroup (see of-builder for an example of this) to build them parallel, but with a limit applied so that the concurrency is manageable - i.e. 2 or 4 at once.

The errgroup can be used to synchronise and collect any errors that come up.

Serial deployment loop:

https://github.com/openfaas/openfaas-cloud/blob/master/git-tar/function/ops.go#L319

errgroup usage:

https://github.com/openfaas/openfaas-cloud/blob/master/of-builder/main.go#L196

**Comment by AkihiroSuda** [comment]
Does https://github.com/abarnert/errpool work for you?

> Like sync.errgroup but with limited concurrency

**Comment by alexellis** [comment]
Perhaps we could implement our own variation rather than the the technical debt/dependency? There's similar code in the faas-cli build command too.

**Comment by alexellis** [comment]
Derek add label: Hacktoberfest

**Comment by ivanayov** [comment]
Derek assign: me
