### ISSUE TITLE
UI: Dashboard - offer logout button when JWT present

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#256]
## Expected Behaviour

In the UI: Dashboard we must offer a logout button (only when the cookie/JWT is present). 

This can be detected by looking for a Cookie in the headers:

https://github.com/openfaas/openfaas-cloud/blob/3d3ed09707817b436751b279973d6f26191930a4/auth/handlers/const.go#L4

Clearing this Cookie should be sufficient.

## Current Behaviour

User must clear the Cookie manually.

**Comment by bartsmykla** [comment]
Derek assign: me
