### ISSUE TITLE
Edit git-tar raw URL stack file optimisation to support both GitHub/GitLab

### ISSUE THREAD

**Issue by martindekov** [openfaas/openfaas-cloud#276]
This commit https://github.com/openfaas/openfaas-cloud/commit/aa5828702f0e82f5b1070cb1c1b73ff908ceb4e3 adds optimization for git-tar but I think the format of the URL in this line https://github.com/openfaas/openfaas-cloud/commit/aa5828702f0e82f5b1070cb1c1b73ff908ceb4e3#diff-6972f28fc33acdd0e2082babf8ec8405R276 should be moved away from git-tar possibly sent through github-push or github-event to the git-tar so the function itself is non dependent on github or any SCM

## Expected Behaviour

URL to be formatted in github-push or github-event rather than git-tar. Move away SCM specific field out of git-tar.

## Current Behaviour

Git-tar suggest only github raw formatting

## Possible Solution

Format the URL in github-event or github-push function and send it to git-tar.

## Steps to Reproduce (for bugs)

It is not a bug per se

## Context

It is currently blocking #275 since the format of the URL is wrong for gitlab. And the workaround I am currently using is to set the `private_repo:true` all the time for gitlab, which is not the case. Also I think it is a good thing to keep functions down from git-tar away from SCM specific code.

**Comment by martindekov** [comment]
Derek add label: design/review

**Comment by ivanayov** [comment]
As it is now, git-tar will always fail for GitLab.
We should should move the URL only, but leave the optimisation here.

I can work on this.

**Comment by ivanayov** [comment]
Derek assign: me

**Comment by ivanayov** [comment]
Derek set title: Edit git-tar raw URL stack file optimisation to support both GitHub/GitLab
