### ISSUE TITLE
Issue with GitLab OAuth 2.0 provider and redirect URL

### ISSUE THREAD

**Issue by bartsmykla** [openfaas/openfaas-cloud#277]
GitLab `Web Application Flow` (which we are using for getting token from GitHub) is stricter than GitHub and forbids to add any additional params to query for authorization code (`https://gitlab.example.com/oauth/authorize?client_id=APP_ID&redirect_uri=REDIRECT_URI&response_type=code&state=YOUR_UNIQUE_STATE_HASH`) so we need to remove it from query, and probably put to headers?

## Possible Solution

Moving `r=https://system.domain.com/dashboard` from query string to headers

## Context

I was trying to figure out why GitLab is giving me `authorization code` but when I tried to use it for getting `access token` I was receiving 401 in response with message:
```
The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.
```
after investigation it appeared that if we use any additional query parameters in request for `authorization code` we will always receive 401 in response of request for `access token`

**Comment by alexellis** [comment]
Derek add label: design/review

**Comment by alexellis** [comment]
(Change not approved.)

**Comment by alexellis** [comment]
I can actually make this work even using a custom parameter in my redirect URL.

`Callback URL`: `http://localhost:8081/oauth2/authorized`

Running it:

```
base_url=https://gitlab.your-host client_secret=$client_secret client
_id=$client_id port=8081 go run main.go
```

```
2018/10/10 12:57:57 Using port: 8081
2018/10/10 12:57:58 URL: /oauth2/authorized?custom_param=1&code=xyz&state=state
2018/10/10 12:57:58 map[custom_param:[1] code:[xyz] state:[state]]
```

**Comment by alexellis** [comment]
My GitLab version: GitLab Enterprise Edition 11.1.4-ee d17962f

(Remember I asked the team to not install the Kubernetes package but to install directly onto an Ubuntu host, perhaps you have an old version?)

Alex

**Comment by bartsmykla** [comment]
I have installed directly, not using kubernetes, but Community Edition version.
```
GitLab Community Edition 11.3.4 30f019d 
```

**Comment by alexellis** [comment]
Also works fine on this version: `GitLab Enterprise Edition 11.3.4-ee 14d3a1d`

Please use my code Gist with your installation.

**Comment by bartsmykla** [comment]
Problem is, that request for `authorization code` - `https://gitlab.example.com/oauth/authorize?client_id=APP_ID&redirect_uri=REDIRECT_URI&response_type=token&state=YOUR_UNIQUE_STATE_HASH` is working without a problem with additional parameters. But when I'll try to use the code from response in next request for jwt `access token` I'm receiving the error above. When I'll remove additional query params I'm being passed.

**Comment by DouweM** [comment]
@bartsmykla Can you share the exact request (method, URL, params) you're issuing, that results in the `The provided authorization grant...` error?

Is it the request in https://docs.gitlab.com/ee/api/oauth2.html#1-requesting-authorization-code, https://docs.gitlab.com/ee/api/oauth2.html#2-requesting-access-token, or another request entirely?

**Comment by alexellis** [comment]
Derek set title: Issue with GitLab OAuth 2.0 provider and redirect URL

**Comment by alexellis** [comment]
Maybe show whatever issue you're facing by adapting the Gist I provided? That will remove the risk of user error and mean anyone else can provide input. @DouweM from GitLab has added some input.

**Comment by DouweM** [comment]
> It seems odd to me that GitLab's API requests a redirect_uri (which serves no obvious purpose) in order to exchange the "code" for a token.

@alexellis Note that this is in line with the OAuth2 spec: https://tools.ietf.org/html/rfc6749#section-4.1

```
   (D)  The client requests an access token from the authorization
        server's token endpoint by including the authorization code
        received in the previous step.  When making the request, the
        client authenticates with the authorization server.  The client
        includes the redirection URI used to obtain the authorization
        code for verification.
```

**Comment by alexellis** [comment]
It seems that you're technically right (as per the RFC), but I've not seen it done in practice with GitHub, Strava etc.

@bartsmykla have you tried the example I posted which shows a token being retrieved end-to-end?

**Comment by alexellis** [comment]
Derek close: working as designed

**Comment by alexellis** [comment]
Feel free to keep commenting.
