### ISSUE TITLE
Evaluate/switch to "moby" build of buildkit

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#282]
## Expected Behaviour

@AkihiroSuda let me know that there's an image being published via the `moby` account on the Docker Hub now: `moby/buildkit:master` and `moby/buildkit:master-rootless`

We should evaluate whether these updated images work seamlessly with the templates used on OpenFaaS Cloud and then switch over.

I'd also recommend pinging the buildkit maintainers and requesting pinned versions by date or commit SHA so that we don't have any breakage by inadvertently taking a version with a bug/issue/regression/breaking change.

## Steps to Reproduce (for bugs)

Test with the offical templates along with [node8-express](https://github.com/openfaas-incubator/node8-express-template) and [golang-http](https://github.com/openfaas-incubator/golang-http-template).

Once evaluated including adding custom modules via `pip` for Python or `npm` for node and `gem` for Ruby (etc) - update the YAML files and .md files where we reference the custom buildkit version built under my own username alexellis/alexellis2.

## Scenarios

| Template                  |  Only changing handler      |  With static files        |  With 3rd-party dependencies |
-----------------------------|------------------------------------|-----------------------------|-----------------------------------------|
| Node                        |                                            |                                 |                                                  |
| Python 2.7            |                                            |                                 |                                                  |
| Python 3               |                                            |                                 |                                                  |
| Ruby                    |                                            |                                 |                                                  |
| Golang            |                                            |                                 |                                                  |
| CSharp                     |                                            |                                 |                                                  |
| Java                       |                                            |                                 |                                                  |
| Golang HTTP            |                                            |                                 |                                                  |
| Golang Middleware   |                                            |                                 |                                                  |
 Node8-express         |                                            |                                 |                                                  |

**Comment by AkihiroSuda** [comment]
now tagged images are available: https://hub.docker.com/r/moby/buildkit/tags/

**Comment by viveksyngh** [comment]
Derek Assign: me

**Comment by viveksyngh** [comment]
Sharing Progress: 

1. Deployed `moby/buildkit:v3.0.0` using below command 

```sh
docker run -d --net func_functions -d --privileged \
> --restart always \
> --name of-buildkit moby/buildkit:v0.3.0 --addr tcp://0.0.0.0:1234
```

2. Committed code to this repo https://github.com/faas-furious/of-cloud-test-fn which deployed two functions which are using `python` and `golang` template.

**Comment by alexellis** [comment]
I'm not seeing the status URLs populated or links for the functions?

**Comment by viveksyngh** [comment]
Yes, I will debug that.

**Comment by viveksyngh** [comment]
The status update was due to issue with Github App permission. I have updated it and it is working.

https://github.com/faas-furious/of-cloud-test-fn/runs/24705556

**Comment by alexellis** [comment]
Great. I've added a grid to the issue to help with the testing @viveksyngh

**Comment by viveksyngh** [comment]
I have tested with `python` and `golang` template. I have the plan to test other scenarios this weekend.

**Comment by viveksyngh** [comment]
Node |   |   |  
Python 2.7 |   |   |  
Python 3 |   |   |  
Ruby |   |   |  
Golang |   |   |  
CSharp |   |   |  
Java |   |   |  
Golang HTTP |   |   |  
Golang Middleware |   |   |  
Node8-express |   |

**Comment by viveksyngh** [comment]
Template | Only changing handler | With static files | With 3rd-party dependencies
--- | --- | --- | ---
Node |   |   | 
Python 2.7 |   |   |
Python 3 |   |   |
Ruby |   |   |
Golang |   |   |
CSharp |   |   |
Java     |    |    |
Golang HTTP |  |  |
Golang Middleware |  |  |
Node8-express  |   |   |

**Comment by viveksyngh** [comment]
All functions are deployed here. http://system.vs.team-serverless.xyz:8081/dashboard/viveksyngh/
