### ISSUE TITLE
NIC management on running server?

### ISSUE THREAD

**Issue by MineMS49** [openfaas/openfaas-cloud#285]
Is it posible to manage all network interfaces and ports used by OpenFaas while running on a server ?
By default OpenFaas register itself on each network interfaces using ports, like the :8080 for the UI or :9090 for Prometheus.
For NIC management purposal it could be a great enhancement to add on the UI a new tab. Also I didn't find helpful advice in this OpenFaas gitHub (If this question is already solved I didn't noticed it), so a read me more detailed on technical aspect will really help in building infrastructure using OpenFaas.

**Comment by alexellis** [comment]
Hi @MineMS49 I think this question makes more sense on the openfaas/faas repo?

How about you move it there and fill in the entire template with all the information we require?

Thanks,

Alex

**Comment by alexellis** [comment]
Derek lock: wrong repo
