### ISSUE TITLE
authz: Restrict dashboard functions to logged-in user and organisations

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#289]
## Expected Behaviour

Only when auth is enabled (JWT present) then as user (x) I should only see my own functions and any functions belonging to the organisations I'm a member of i.e .(a, b, c).

## Current Behaviour

I can see anyone's functions or any organisation by changing the URL.

## Possible Solution

If a JWT is present, then read the claims of the JWT and then show the union of functions via `list-functions`

Related #278 #234

**Comment by ivanayov** [comment]
Derek unassign: me

**Comment by alexellis** [comment]
I think we need to wait until the organisations are in place before we do this otherwise we won't be able to work with functions on organisations if this is done before.

**Comment by ivanayov** [comment]
We have the orgs now, so I can work on this

**Comment by Waterdrips** [comment]
/ assign me

**Comment by Waterdrips** [comment]
Derek assign: me
