### ISSUE TITLE
Update status if stack.yml not present in repo

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#31]
## Scenario

User generates a function named fn1 with fn1.yml and doesn't rename it to stack.yml. OpenFaaS Cloud always looks for stack.yml in the root of the repo, so this won't build and the user will never find out the reason.

## Error

This generates a build error, so we should inform them about it via the Statuses API:

```
# docker service logs git-tar  -f
git-tar.1.3y8ges2e9qma@openfaas-cloud    | 2018/04/29 07:45:36 Writing lock-file to: /tmp/.lock
git-tar.1.3y8ges2e9qma@openfaas-cloud    | 2018/04/29 07:45:48 Forking fprocess.
git-tar.1.3y8ges2e9qma@openfaas-cloud    | 2018/04/29 07:45:48 Query  
git-tar.1.3y8ges2e9qma@openfaas-cloud    | 2018/04/29 07:45:48 Path  /
git-tar.1.3y8ges2e9qma@openfaas-cloud    | 2018/04/29 07:45:48 Success=false, Error=exit status 255
git-tar.1.3y8ges2e9qma@openfaas-cloud    | 2018/04/29 07:45:48 Out=2018/04/29 07:45:48 parseYAML  open /tmp/go-fns-tester/stack.yml: no such file or directory
git-tar.1.3y8ges2e9qma@openfaas-cloud    | 
```

**Comment by ericstoekl** [comment]
Derek assign: me

It looks to me like it's necessary to separate out the `reportStatus` method and expose it in the `sdk` package. Otherwise, we'll be repeating a lot of the same code in order to create the Status API call. Am I correct in this assumption?

**Comment by ericstoekl** [comment]
Derek assign: me

**Comment by alexellis** [comment]
I am OK with some duplication up front until we work out what the API should be. Looking at what to move into SDK is also good input.

**Comment by alexellis** [comment]
Moving over to Vivek after several weeks of inactivity.

**Comment by viveksyngh** [comment]
@alexellis When there is an error with parsing the `stack.yml` or `stack.yml` is not present we are reporting the error status in GitHub. 

Should explicitly check whether `stack.yml` file is present or not before parsing it and report the status?
