### ISSUE TITLE
Send proxy variables to buildkit

### ISSUE THREAD

**Issue by WTFKr0** [openfaas/openfaas-cloud#310]
Is there a way to forward of-builder proxy env vars to build-kit ?

## Expected Behaviour
We try to have a fully on-premise openfaas-cloud
We have to build our functions locally as some depends on local resources
We too need to access to the internet through a corporate proxy

## Current Behaviour
Buildkit seems to ignore proxy configuration 

## Possible Solution
In buildkit, there is a way to place build-args through FrontendAttrs
I think of-builder can place them if they are declared as env var in of-builder

## Your Environment
* Docker version `docker version` (e.g. Docker 17.0.05 ):
18.03.1-ce

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Container Linux by CoreOS 1745.7.0 (Rhyolite)

**Comment by ivanayov** [comment]
Derek add label: question

**Comment by bartsmykla** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Approved :+1: we'll try to get this turned around quickly for you to keep you moving forward. Please see my notes on the PR.
