### ISSUE TITLE
github-push: Add user id support.

### ISSUE THREAD

**Issue by martindekov** [openfaas/openfaas-cloud#313]
Currently the user is recognized mainly through the username. Which is not unique and can be changed. We should add user ID to the struct and apply it as label through `buildshiprun`.

## Expected Behaviour

Add handling for user ID in `PushEvent` struct handle it then add it as label through `buildshiprun`

## Current Behaviour

We don't support `buildshiprun`

## Possible Solution

Extend struct in SDK and send to buildshiprun to be applied as label to the function

## Steps to Reproduce (for bugs)

This is a feature

## Context

User ID is constant and cannot be changed. Username can be changed.

**Comment by martindekov** [comment]
Derek assign: me

**Comment by martindekov** [comment]
This was implemented in [git-tar](https://github.com/openfaas/openfaas-cloud/commit/a74e4818d756c998fe252996ad75a57ca4d3795a) and [buildshiprun](https://github.com/openfaas/openfaas-cloud/commit/320c940501d868c471f1c74efca5995203e57255)

**Comment by alexellis** [comment]
Thanks for the update and for the git commits 👍 can you confirm that you have the data flowing through to your functions from OpenFaaS Cloud?

**Comment by martindekov** [comment]
Ok no problems
