### ISSUE TITLE
Dashboard: Repo links invalid with upper-case/mixed-case

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#315]
## Expected Behaviour

Both URLS should work the same for mixed-case usernames:

https://system.o6s.io/dashboard/lucasroesler
https://system.o6s.io/dashboard/LucasRoesler

## Current Behaviour

This URL works fine:

https://system.o6s.io/dashboard/lucasroesler

This one gives invalid links and names:

https://system.o6s.io/dashboard/LucasRoesler

> error finding function lucasroesler-lucasroesler-recho: server returned non-200 status code (404) for function, lucasroesler-lucasroesler-recho

<img width="401" alt="screen shot 2018-10-29 at 3 35 09 pm" src="https://user-images.githubusercontent.com/6358735/47661087-438eb680-db90-11e8-803c-733db6ea7ebf.png">

**Comment by s8sg** [comment]
I started working on it as of #228. Can I continue?

**Comment by alexellis** [comment]
@s8sg do you have any progress on this to report? Do you want this one? We're kind of blocked right now.

**Comment by alexellis** [comment]
Saw this for @Waterdrips - the URL should be: https://waterdrips.o6s.io/helloworld but says: "https://waterdrips.o6s.io/waterdrips-helloworld"

**Comment by alexellis** [comment]
I have fixed this in master for the invocation count / query and the HTTPS endpoinnt URL.

Deployments are only in lowercase, so the username needs to be sent to toLower() before being used to construct links or queries so that it matches the expected pattern in the deployment/Pod.

Alex

**Comment by alexellis** [comment]
@martindekov someone reported this issue is still occurring with a username "MikeFeith", could you try to repro with a new username of your own?

**Comment by MikeFeith** [comment]
> @martindekov someone reported this issue is still occurring with a username "MikeFeith", could you try to repro with a new username of your own?

I get this \/
![Screenshot 2019-09-30 at 10 32 25](https://user-images.githubusercontent.com/23695684/65862026-a4f57180-e36d-11e9-8f30-e1adfbe5d1bd.png)

The link should be this: https://mikefeith.functionasaservice.online/demo
