### ISSUE TITLE
Make validation on by default for hmac/customers

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#316]
## Expected Behaviour

If I mis-configure my system or leave a line out, I still want a secure experience that validates HMAC and the customers list. I.e. they should be on by default (even if no env/YAML setting is et)

So we can still turn these off, but by explicitly adding `validate_customers: false` etc into the YAML file. This means that you as a user/operator are deliberately choosing to turn it off.

## Current Behaviour

If I comment out the line for these values they get turned off.

## Possible Solution

* Update in SDK if necessary then re-release / re-vendor.
* Update consuming code and services
* Update docs on turning off

## Testing

Test that the validation is present for each function when the settings are commented out in the files.

The `faas-cli` has a new method to sign function bodies too (which we can use for the positive test)

**Comment by ivanayov** [comment]
Yep, I can take this

**Comment by martindekov** [comment]
@ivanayov Did you start working on this ?

**Comment by ivanayov** [comment]
@martindekov Yep, I've started

**Comment by ivanayov** [comment]
We talked with @martindekov that he'll test and open a PR, as he is looking for an issue to take, and I am currently preparing a demo for ISTA Conf.

Changes required for a PR:
* Remove length check in [derek/auth/customers.go](https://github.com/alexellis/derek/blob/master/auth/customers.go#L37)

* Revendor git-tar and github-status

* Change [readBool()](https://github.com/openfaas/openfaas-cloud/blob/master/github-event/handler.go#L321) to:
```
func readBool(key string) bool {
	if val, exists := os.LookupEnv(key); exists {
		return val != "false" && val != "0"
	}
	return false
}
```

* Unit and live test

**Comment by martindekov** [comment]
Ok thanks for the progress update @ivanayov

**Comment by martindekov** [comment]
Derek assign: me
