### ISSUE TITLE
Validate custom template URLs

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#319]
## Expected Behaviour

We should validate that custom template URLs are well-formed URLs.

http and https should both be valid.

## Current Behaviour

We don't

## Possible Solution

This is part of the review feedback of : https://github.com/openfaas/openfaas-cloud/pull/264

**Comment by alexellis** [comment]
Please update the unit tests to handle errors when the URLs are invalid and reduce the level of nesting/indent as per - https://github.com/openfaas/openfaas-cloud/pull/320/files#r229253436

**Comment by alexellis** [comment]
Additional comments: https://github.com/openfaas/openfaas-cloud/pull/320#discussion_r229260827

**Comment by ivanayov** [comment]
@alexellis addressed your comments in #321
