### ISSUE TITLE
GitLab commit status - add hyperlinks

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#323]
## Expected Behaviour

The GitLab commit status can support a `target_url`, so we could link to the function endpoint in a successful status, or the dashboard / pipeline-logs in a failed status.

https://docs.gitlab.com/ee/api/commits.html#post-the-build-status-to-a-commit

We could also add comments - for instance the failed container build logs for a bad function build. For instance your Golang function isn't valid due to formatting errors.

https://docs.gitlab.com/ee/api/commits.html#post-comment-to-commit

## Current Behaviour

The user should navigate to the dashboard manually.

**Comment by martindekov** [comment]
Once we settle on this I can work on it since it is in my domain

**Comment by martindekov** [comment]
Derek assign: me

**Comment by ivanayov** [comment]
I'm still wondering if pointing to the old code is needed. One can always check it in the repo alone.
Linking to logs makes more sense IMO.

I'd vote for option 2.
