### ISSUE TITLE
Dashboard: ship dist folder in final stage of Docker build

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#325]
## Expected Behaviour

Dashboard: ship dist folder in final stage of Docker build

## Current Behaviour

We do `make` which takes `src` into a Node container, runs web pack and emits `dist` folder which is then built into a new container. We can streamline process and avoid any permissions issues.

**Comment by alexellis** [comment]
I'm pretty sure we'll have to stop using a function deployment type and start using a custom Dockerfile.

@bartsmykla please use `faas-cli build --shrinkwrap` then base the code on what ends up in the "build/function-name" folder.

**Comment by bartsmykla** [comment]
@burtonr sorry for not responding to you, but I missed the message, before I started working on it. I created PR for that change: https://github.com/openfaas/openfaas-cloud/pull/338 I would be very grateful if you could look on it with @alexellis and give your opinions
