### ISSUE TITLE
Dashboard: Last GitLab repository link to be fixed

### ISSUE THREAD

**Issue by martindekov** [openfaas/openfaas-cloud#334]
Every link works except one for GitLab

## Expected Behaviour

Link in this place to point to GitLab if the function is from there:

![image](https://user-images.githubusercontent.com/34942004/48552351-05f49200-e8e1-11e8-8523-ea598f792d8a.png)

## Current Behaviour

Formats the repository Link for GitHub

## Possible Solution

Get annotation from `list-functions`/`system-list-functions` depending on your configuration and apply whole repository URL from there

## Steps to Reproduce (for bugs)

1. Deploy GitLab
2. Deploy Dashboard
3. Push function to GitLab repo
4. Press the link
5. See GitHub 404

## Context

Affecting Users who are on GitLab and use Dashboard

**Comment by alexellis** [comment]
Please can you link to the PR here ? @martindekov

**Comment by martindekov** [comment]
There is not PR with this change

**Comment by Waterdrips** [comment]
This was fixed as part of this commit https://github.com/openfaas/openfaas-cloud/commit/611b82f931674b16ea7d6d0c9d9b1d47b773617a

which was part of a larger PR
