### ISSUE TITLE
Issue: case-sensitive usernames are not supported by the router

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#34]
The HTTPS router that gives a sub-domain to each user will not support a username like @BurtonR - burtonr would be fine though.

> An Internet address is only case sensitive for everything after the domain name. 

https://www.computerhope.com/issues/ch000709.htm

It would be simple to have the functions deployed with lowercase metadata for usernames - this would resolve the problem. The `Git-Owner` label should be updated in the `buildshiprun` function.

**Comment by martindekov** [comment]
Derek close: This has been addressed and tested `https://martindekovwat.o6s.io/goforfun` original name: `https://MartinDekovWat.o6s.io/goforfun` lead to the same endpoint
