### ISSUE TITLE
UI Dashboard: Change reading index.html to async

### ISSUE THREAD

**Issue by bartsmykla** [openfaas/openfaas-cloud#340]
Referring to this comment: https://github.com/openfaas/openfaas-cloud/pull/295#pullrequestreview-175725899 it would be good to change `readFileSync` to `readFile`
## Expected Behaviour
file `index.html` should being read asynchronously

## Current Behaviour
file `index.html` is being read synchronously

**Comment by alexellis** [comment]
Derek add label: design/approved

**Comment by bartsmykla** [comment]
Derek assign: me
