### ISSUE TITLE
UI: Dashboard - moving from create-react-app to vanilla webpack

### ISSUE THREAD

**Issue by bartsmykla** [openfaas/openfaas-cloud#345]
I think that `create-react-app` is a great tool for starting UI project, but it's very very heavy and hard to configure it for project's needs later, and I think that it's the best time to move from it to vanilla webpack configuration.
## Expected Behaviour
Have simple, tailored for our needs configurations of webpack, babel etc.

## Current Behaviour
We are forced to use predefined plugins, even if in 90% we are not using them, and in many cases reconfiguration is not possible, or very hard.

## Possible Solution
Ejecting app, and then reconfiguring it for our needs. But create-react-app is very complex, and configuration is very long and I think that unnecessary and it'll be better to just decide which functionalities we are using and configure webpack from beginning.

**Comment by alexellis** [comment]
Hi Bart, thanks for the suggestion. Please can you list some pros and cons of each including the learning curve and maintenance cost?

Do you have an example on another project or GitHub repo that you can share to compare and help the community decide?

**Comment by bartsmykla** [comment]
Closing issue, because of it's age. Feel free to recreate it.
