### ISSUE TITLE
[Feature] Show and filter functions from my orgs in my dashboard

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#347]
## Story

As an OpenFaaS Cloud user visiting my dashboard I want to be able to see my functions plus all the functions belonging to my organisations so that I can collaborate with my team.

This related issue #234 shows where we started to store the claims in the user's JWT token. This can be read in the back-end function of the dashboard and be used to call the `list-functions` function with all the `usernames` vs only the logged in user.

I.e. Alex Ellis (alexellis) is a member of vmware and openfaas, therefore call list-functions for: `[alexellis, openfaas, vmware]`.

## Acceptance criteria (priority order)

1. Given I am a member of organisation X, I can see functions belonging to organisation X in my dashboard Addressed by: #289
2. The sort-order shows my functions first, followed by each org ordered by name using string comparisons
3. I can filter based upon `owner` / organisation using a drop-down in the UI
4. My filter selection is "remembered" / stored in a local cookie.

**Comment by ivanayov** [comment]
Derek assign: me

**Comment by Waterdrips** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Requirements for 1) closes: #289

**Comment by alexellis** [comment]
Requirements for 2) 3) and 4) are closed by: #361
