### ISSUE TITLE
Update garbage-collect to recover old user functions

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#35]
Right now garbage-collect just echoes what it would remove, but it should actually remove orphaned functions where someone has removed a function from a stack or renamed it within a repo.

Additional unit tests should also be added, which may need some abstractions to be added for the HTTP calls / queries to the *list-functions* function and the *delete functions* API.

**Comment by martindekov** [comment]
Derek close: I think this is outdated and now we use GitHub Application for function removing of course if this is not the intent please share it with me
