### ISSUE TITLE
UI Dashboard: Add information about owner of the function

### ISSUE THREAD

**Issue by bartsmykla** [openfaas/openfaas-cloud#359]
Because implementation of supporting functions from organisations is almost finished, it would be good to have some kind of indication about if function is from organisation or the user. The idea is for example if function is from user `bartsmykla` we could see small icon with letter `b` if function is from organisation `openfaas-cloud` we could see small icon with letters `oc` etc.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by ivanayov** [comment]
I'm working on it

**Comment by bartsmykla** [comment]
Closing issue, because of it's age. Feel free to recreate it.
