### ISSUE TITLE
UI Dashboard: bug with progress bar wrongly showing number of replicas

### ISSUE THREAD

**Issue by bartsmykla** [openfaas/openfaas-cloud#365]
Progress bar is showing always 1/4. Even when there is 4/4 replicas currently working.

## Expected Behaviour
Correctly display number of replicas in progress bar.

## Current Behaviour
Progress bar is showing always 1/4. Even when there is 4/4 replicas currently working.

## Steps to Reproduce (for bugs)

1. Scale up function replicas

**Comment by alexellis** [comment]
Thanks for logging this.

**Comment by alexellis** [comment]
<img width="1170" alt="screen shot 2018-12-18 at 12 51 35 pm" src="https://user-images.githubusercontent.com/6358735/50157809-47a29f00-02ca-11e9-8e77-7cc5439d3362.png">
