### ISSUE TITLE
Add liveness and readiness probes to Deployments in core YAML

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#376]
## Expected Behaviour

Add liveness and readiness probes to Deployments in core YAML

https://github.com/openfaas/openfaas-cloud/tree/master/yaml/core

We should also add the Prometheus annotation to prevent scraping by Weave cloud. See the openfaas/faas-netes repo for an example of this

**Comment by martindekov** [comment]
Derek assign: me
