### ISSUE TITLE
router - apply HTTP tuning as per openfaas/faas gateway

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#382]
## Description 

In the router component (./router) a HTTP client is used to forward requests to the auth service and specific routes/URLs on the gateway. In the gateway we are doing some performance tuning to help relieve pressure on CoreDNS in Kubernetes via https://github.com/openfaas/faas/pull/1039.

The solution for the gateway should be evaluated to see if they are also required here by doing the same testing described with `hey`.

Note: for performance testing rate-limiting on the ingress controller should be turned off to prevent any false negatives.

**Comment by alexellis** [comment]
openfaas/faas#1039 has now been merged and released so we should start this work.

**Comment by viveksyngh** [comment]
I will work on this one.

**Comment by viveksyngh** [comment]
Derek assign: me

**Comment by alexellis** [comment]
I took this and made the changes
