### ISSUE TITLE
Ideas for the OpenFaas documentation 

### ISSUE THREAD

**Issue by burf2000** [openfaas/openfaas-cloud#397]
Hi Alex, here are some pointers to make this document a little more newbie friendly

https://github.com/openfaas/openfaas-cloud/blob/master/docs/README.md

Edit github.yml and populate with your GitHub App ID:
- Where does github.yml come from?  are we starting off with something?

For the queue-worker, set the ack_wait field to 15m to allow for a Docker build of up to 15 minutes total.
- Maybe a link to how to do this?

WEBHOOK_SECRET="Long-Password-Phrase-Goes-Here"
echo -n "$WEBHOOK_SECRET" | docker secret create github-webhook-secret -
- What password goes here?  Do we make this up

After reading some more of the doc, I bailed as I do think you need to know a lot more to get this working
gateway_config.yml.? Should I already have this file?
Again buildshiprun_limits.yml?

**Comment by ivanayov** [comment]
Hi @burf2000,
Do you still need help with the set-up or this is just a proposal how to make the first experience better?
A good option is to try the deployment tool - [ofc-bootstrap](https://github.com/openfaas-incubator/ofc-bootstrap) where the manual configuration is minimal and OpenFaaS Cloud is deployed in less than a minute.

**Comment by alexellis** [comment]
Thanks for the suggestions @burf2000

**Comment by alexellis** [comment]
I think we've covered this with the bootstrap tool mentioned by @ivanayov

**Comment by JokerQyou** [comment]
The bootstrap tool is only available for k8s environment. If some how someone (myself for example) only has access to docker swarm environment, he'd still need these manual instructions in the doc. I've searched through openfaas-cloud and openfaas documentation and yet have no luck learning how to set these said values. So yes, I think I need help with the set-up.
