### ISSUE TITLE
Optimisation (status): Use token forwarding and status grouping to avoid extra calls

### ISSUE THREAD

**Issue by s8sg** [openfaas/openfaas-cloud#41]
> This suggestion consider `git-status` as a openfaas function for status update

### Group multiple status update in an array
When required to update multiple status at a time, rather than making a separate call for each status, multiple statuses can be grouped and forwarded at once

#### Possible Solution

**1. Accept multiple commit status in `git-status`**
`git-status` can be changed to accept more than one status at a single execution

**2. Sdk to abstract combine multiple status in a single call**
This can be abstracted by the `sdk` for `Status`
Example:
```
status := BuildStatus()

// add status
status.Add(context1, status1)
// add status
status.Add(context2, status2)

// same status object can store the token from earlier call 
status.Report()
}
```  
In the above example status1 and status2 is forwarded at a single call to `git-status`

**3. Avoid status that will be overridden**
Github map status based on context, which overrides status for same context. Which means for a call sequence like below, the status1 will be overridden by status2 in github
```
status := BuildStatus()

// add status
status.Add(context1, status1)
// add status
status.Add(context1, status2)

// same status object can store the token from earlier call 
status.Report()
}
```
To avoid an extra call the grouped status can be mapped against the context, that will avoid extra call for status that going to be overridden, i.e.
```
CommitStatuses map[string]CommitStatus // context -> CommitStatus
```

### Avoid Authentication by Forwarding the Token

Authentication makes an extra Http call for each status update. 
As the function are stateless, it is (not recommended/ impossible) to store token on functions

#### Possible Solution

**1. Return Token on Success**
`auth-token` can be returned from the `git-status` function on authentication so that it can be reused

**2. Status SDK**
status sdk is meant to abstract the call to `git-status` call. `Status` sdk can itself be used for abstract the call to `git-status`.   
It can be used to abstract the `token` reuse mechanism for multiple `status` update from a single execution of a function 
example: 
```
status := BuildStatus()
Loop {
      // add status
      status.Add(..)
      // same status object can store the token from earlier call 
      status.Report()
}
```  

**3. Forward token to FaaS function**

Token can be forwarded from one function to another, so that it can be reused. 
It can be achieved by setting it either in `http_header` or as a part of data
And can be passed while creating the status 
```
status := BuildStatus(os.Getenv(Http_Token)
```

#### Possible Definition for Status sdk
```
const (
        Success = "success"
        Failure = "failure"
        Pending = "pending"
)

// context constant
const (
 //       Build  = "%s_build"
        Deploy = "%s_deploy"  // function1_deploy 
        Stack  = "stack-deploy"
)

type CommitStatus struct {
        Status      string `json:"status"`
        Description string `json:"description"`
        Context     string `json:"context"`
}

// Status to post github-status to git-status function
type Status struct {
        CommitStatuses map[string]CommitStatus `json:"commit-statuses"`
        EventInfo      Event                   `json:"event"`
        AuthToken      string                  `json:"auth-token"`
}

// builds a status
func BuildStatus(event *Event, token String) *Status

// Unmarshal a status from json byte array
UnmarshalStatus(data []byte) (*Status, error)

// Add a status to status object
func (status *Status) AddStatus(status string, desc string, context string) 

// Marshal a status Object
func (status *Status) Marshal() ([]byte, error)

//  send a status update to git-status function, and store token in object 
func (status *Status) Report(gateway string) (string, error) 
```

**Comment by alexellis** [comment]
This is two different issues. I would like to see them implemented separately rather than together.

The idea to add the statuses together in a transaction and then report at the end is useful, as long as there are no panics or other issues like a nil deference.

**Comment by s8sg** [comment]
derek close
