### ISSUE TITLE
dashboard fails to deploy. missing image in docker hub (functions/of-cloud-dashboard:0.4.0)

### ISSUE THREAD

**Issue by mbarlow** [openfaas/openfaas-cloud#415]
## Expected Behaviour

deploy should create the dashboard

## Current Behaviour

kubernetes shows: ErrImagePull for functions/of-cloud-dashboard:0.4.0
# Possible Solution

push the image to docker hub

## Steps to Reproduce (for bugs)

1. deploy to kubernetes using ofc-bootstrap project
2. kubectl describe pod system-dashboard -n openfaas-fn 
3. verify pod failing to be created

## Context

cannot use dashboard

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.8.3

* Docker version `docker version` (e.g. Docker 17.0.05 ): 18.09.2

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS): MacOs Mojave

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
Thank you for reporting this. Please update the deployment to use an older version - look at the Docker Hub to find that.

A PR from the community was merged recently in this area. I'll double check the image was pushed for the change.

**Comment by alexellis** [comment]
Derek close: image pushed
