### ISSUE TITLE
Docs: Update docs/README.md with custom template instructions

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#419]
## Task

Relates to #417 

We have a request from a user for documentation on setting custom templates.

Document in docs/README.md:

* How to edit in-flight (edit git-tar deployment on Kubernetes)
* Edit the relevant YAML file and deploy git-tar selectively

YAML file: https://github.com/openfaas/openfaas-cloud/blob/master/gateway_config.yml#L11

**Comment by alexellis** [comment]
@martindekov / @zeerorg?

**Comment by martindekov** [comment]
I can do that 👍

**Comment by martindekov** [comment]
Derek assign: me

**Comment by martindekov** [comment]
Done [here](https://github.com/openfaas/openfaas-cloud/pull/420) 👍
