### ISSUE TITLE
Support for Dockerfiles template in self-hosted clusters

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#421]
## Expected Behaviour

We should make support available for the "dockerfile" template on self-hosted clusters.

## Current Behaviour

Unavailable see: #417 

## Possible Solution

* A flag is needed for OpenFaaS Cloud to enable use of the dockerfile template - validate this in the git-tar function
* This flag should be off by default
* Update git-tar's Dockerfile to use the latest faas-cli
* Test e2e

~~Explore what is missing in the code (probably the `faas-cli build --shrinkwrap` code is unavailable.~~

~~The `--shrinkwrap` option produces a directory which can be made into a tar for usage with an external Docker builder. On OFC this is Buildkit.~~

## Steps to Reproduce (for bugs)

1. Deploy OFC
2. `faas-cli new --lang dockerfile fn`
3. `mv fn.yml stack.yml`
4. Commit to Git repo

## Context

This must be turned off by default so that it's not deployed into the Community Cluster.

**Comment by alexellis** [comment]
We'll need to update git-tar to use a new release of the faas-cli.

**Comment by alexellis** [comment]
https://github.com/openfaas/faas-cli/pull/new/alexellis/shrinkwrap-dockerfile

**Comment by alexellis** [comment]
CLI version should be 0.8.6 now.

**Comment by matipan** [comment]
I can take over this one :+1: I'll try the changes on my ofc installation

**Comment by matipan** [comment]
And it's working https://github.com/matipan/dtest/runs/84836104 ! :champagne:

**Comment by matipan** [comment]
And here it's the message when a dockerfile function is detected but the feature is disable: https://github.com/matipan/dtest/runs/84843643

**Comment by alexellis** [comment]
I'm impressed! That looks great :+1:

Let me know when you have a PR up. 

Alex

**Comment by matipan** [comment]
PR is up :point_up:
