### ISSUE TITLE
Feature: Support CI/CD from multiple branches to corresponding environments

### ISSUE THREAD

**Issue by sachin-dhamane** [openfaas/openfaas-cloud#425]
We keep long term projects that have longer testing cycle on a different branch. We need ability to have a dedicated environment per branch for CI/CD. After necessary testing, features from these branches will merge back to master which will point to production environment. This allows better control over developing features without losing the CI/CD during development.

## Expected Behaviour

There should be ability to specify which OpenFaaS environment is listening for GitHub events from which branch and trigger CD accordingly.

## Current Behaviour

Currently only merges from master trigger CD.

**Comment by alexellis** [comment]
One way this could be implemented at a low cost would be to have separate environments which are configured to only build from a certain named branch. Right now that named branch is `master`, but if we made this a configuration element you could define in the ofc-bootstrap tool then you could provision for instance two environments in around 200 seconds and then get the experience desired.

The `staging` environment would point at the `staging` branch and have a different set of URLs from the `master` environment (or production).

## GitHub validation

Code/check:

https://github.com/openfaas/openfaas-cloud/blob/ad4bb62902af4e597b60914cb03337f03ea5c45f/github-push/handler.go#L69

Test:

https://github.com/openfaas/openfaas-cloud/blob/4899ff2a3d10cd814a160e69e2c305172792e935/github-push/handler_test.go#L30

## stack.yml check

https://github.com/openfaas/openfaas-cloud/blob/7a72c8af543276ff2073d6bb08eefa1e8d87eb1e/git-tar/function/handler.go#L338

## Image reference format

https://github.com/openfaas/openfaas-cloud/blob/ad3fe9abfb1c40c15028034d0ae12599754cb1c0/git-tar/function/ops.go#L183

## UI for formatting GitHub link/URL to branch

https://github.com/openfaas/openfaas-cloud/blob/86852812d678f71b6f1f42b6f3e712a8d5ff585f/dashboard/client/src/components/FunctionTableItem/FunctionTableItem.jsx#L16

All of the above was found from a GitHub search for the text `"master"`. If we made all of this a config item i.e. `build_branch: dev/staging/master/` then it would be relatively straight-forward to set up multiple environments as per the request.

Alex

**Comment by alexellis** [comment]
@martindekov can you confirm that GitLab is only limited to building from the master branch?

**Comment by martindekov** [comment]
Let me check It out will comment with results

**Comment by martindekov** [comment]
```
status: 200 response: refusing to build non-master branch: refs/heads/whatever
```
I red the proposal, seems like a good idea, some people may require dev,staging environments etc. Otherwise, yes we build from master only ATM

**Comment by matipan** [comment]
This is a really good idea. The proposal seems reasonable, make it a config option and modify the affected functions.
We also need to update the ofc-bootstrap after this is implemented.

@martindekov do you plan on working on this or is it ok if I get started?

**Comment by alexellis** [comment]
There seems like quite a few places that need a change, so I would suggest proposing how we will configure it then outline the work and you could both cover it?

* UI changes
* GitHub changes
* GitLab changes
* git-tar changes
* anything else

**Comment by matipan** [comment]
I'd go with using an environment variable. It seems to be straight forward to implement and is backwards compatible since we can default to `master`.

I haven't done any UI development with angular nor react lately although I wouldn't mind to start now.
As for the functions, I've used github and currently have a github installation so I could work on that. If @martindekov has already worked with gitlab and has his own installation then it would be a good idea to leave that to him.

For ofc-bootstrap I was thinking we could modify the names of the namespaces for kubernetes whenever the user specifies something that is not master. This way they could use the tool to bootstrap all of their environments in a single cluster(if that is something desired). The downside is that we will be offering this for kubernetes only since swarm does not have namespaces.

**Comment by martindekov** [comment]
Hey @matipan I need to move some PRs for merging this weekend and I need to finish work on Issue I assigned myself last week, but haven't been able to look at.

I can take this but not sure when exactly I will start working on it, if this is high priority you can take it, or I can start work on it or split the job for GitLab and GitHub part. I would suggest the latter I can take the GitLab part and the `git-tar` and provide you with image containing the change for testing purposes? Tell me what you prefer so we can split it up like a dream team 💯

**Comment by martindekov** [comment]
> For ofc-bootstrap I was thinking we could modify the names of the namespaces for kubernetes whenever the user specifies something that is not master. This way they could use the tool to bootstrap all of their environments in a single cluster(if that is something desired). The downside is that we will be offering this for kubernetes only since swarm does not have namespaces.

I believe this can be achieved with Go templates by adding environmental variables to the `stack.yml` while bootstrapping cloud for the functions which will contain the change(list of branches which the user will use) that way we will not care whether it is swarm or k8s. This can be added like option to the `init.yml`.

**Comment by matipan** [comment]
> Hey @matipan I need to move some PRs for merging this weekend and I need to finish work on Issue I assigned myself last week, but haven't been able to look at.
> 
> I can take this but not sure when exactly I will start working on it, if this is high priority you can take it, or I can start work on it or split the job for GitLab and GitHub part. I would suggest the latter I can take the GitLab part and the `git-tar` and provide you with image containing the change for testing purposes(`git-tar`)? Tell me what you prefer so we can split it up like a dream team 💯

Lets do that if you want 😄 I can start right away on this, so I'll start with the GitHub function. If all goes well maybe I can take git-tar off your plate if you haven't already gotten there.



> > For ofc-bootstrap I was thinking we could modify the names of the namespaces for kubernetes whenever the user specifies something that is not master. This way they could use the tool to bootstrap all of their environments in a single cluster(if that is something desired). The downside is that we will be offering this for kubernetes only since swarm does not have namespaces.
> 
> I believe this can be achieved with Go templates by adding environmental variables to the `stack.yml` while bootstrapping cloud for the functions which will contain the change(list of branches which the user will use) that way we will not care whether it is swarm or k8s. This can be added like option to the `init.yml`.
> 
> [this](https://github.com/openfaas-incubator/ofc-bootstrap/commit/85bb43ec93241331e865487b1379219b73eaad75) commit for example removes secrets from the `stack.yml` same way we can add environmental variables to `git-tar` `gitlab-push` `github-push` ...

I'm not sure I understood. Are you suggesting that the users specify a list of branches in the `init.yml`?

**Comment by martindekov** [comment]
Hey @matipan 

> I'm not sure I understood. Are you suggesting that the users specify a list of branches in the init.yml?

I think keeping the project backward compatible with generally the same UX for Kubernetes and Swarm is a plus. So yeah I think we can approach it that way. Do you find it reasonable? I might be missing something with my proposal.

**Comment by matipan** [comment]
I agree that we should keep it backward compatible. 

My proposal would be that for Kubernetes only we change the name of the namespace to include the branch(in case is not master) so that the users can use the bootstrap to have two different installations of ofc in the same Kubernetes cluster and achieve something a bit similar to what Stefan did in [this blog post](https://www.openfaas.com/blog/gke-multi-stage/). Note that the user would run the tool twice with different values in the `init.yaml` but pointing to the same cluster.

If we can achieve that using Go's templates and provide that functionality for swarm and k8s then it would be great, but I'm not sure how would that work.

**Comment by matipan** [comment]
Derek assign: me

**Comment by matipan** [comment]
CI/CD on different branches for GitHub is starting to shape up:
```
Push - {refs/heads/develop {hello-world-go matipan/hello-world-go https://github.com/matipan/hello-world-go.git false 172135196 https://github.com/matipan/hello-world-go {matipan matipan@users
.noreply.github.com 8126891}} 2179f8029f386acd14f994b6453d0a4315e1bb6b {740767} github}, git-tar status: 202
```
https://github.com/matipan/hello-world-go/runs/97516400

**Comment by matipan** [comment]
@alexellis @martindekov should we switch to using the `BranchAndSHAFormat` for the image name now? 
I'd suggest using this format only if the branch is not master so that existing users aren't affected.

**Comment by martindekov** [comment]
Hey @matipan nice progress, I don't have any yet but when I build git-tar I will provide you with image which will enable building from non-master branches(if you haven't done that already). Otherwise I would suggest to just implement the non-master branch process, and we can think of the image naming further down the line? You can even open issue with the proposal WDYT?

**Comment by matipan** [comment]
@martindekov No problem, I already made the changes to git-tar, is at [matipan/of-git-tar:build_branch](https://hub.docker.com/r/matipan/of-git-tar/tags) :smile: 

Sure, we can address that later :+1:

**Comment by alexellis** [comment]
I'm looking forward to trying it :)

**Comment by alexellis** [comment]
@matipan `BranchAndSHAFormat` sounds fair. Please can you share an example of both formats/examples below?

**Comment by alexellis** [comment]
Hey @matipan is there something we can do to improve this?

Alex

![Screenshot 2019-04-11 at 17 24 22](https://user-images.githubusercontent.com/6358735/55974018-ad060b80-5c7e-11e9-8d15-87656bbe6f38.png)

**Comment by alexellis** [comment]
Would this help? https://github.com/openfaas/faas-cli/issues/617

**Comment by matipan** [comment]
You found my shameful commit :laughing: 
That might help although this is my own problem, I'm constantly reinstalling ofc and I always forget to add the custom templates

**Comment by alexellis** [comment]
How do you install them normally?

**Comment by matipan** [comment]
> @matipan `BranchAndSHAFormat` sounds fair. Please can you share an example of both formats/examples below?

Here are the two formats:
* SHAFormat(current): `go-fns-tester-func:0.2-04b8e44`
* BranchAndSHAFormat(proposed): `go-fns-tester-func:0.2-master-04b8e44`

The final name of the image will depend on the owner, repo and how the registry is specified.

---

> How do you install them normally?

I simply modify the `custom_templates` on ofc bootstrap to include the templates I need. But I often forget about it.

**Comment by alexellis** [comment]
Let's go for your suggestion for the image format. The sha does trace to the branch but we can do this for the purposes of user readability

**Comment by martindekov** [comment]
Hey @matipan Do you have image, which contains the building of the branches, without the sha image name? I am asking since I deployed the image you mentioned above and the git-tar cannot build properly I suppose you are developing on it. If you don't have separate image I can make a hack for now, just asking in case you do.

**Comment by martindekov** [comment]
For `git-tar` ^

**Comment by matipan** [comment]
What error are you seeing when it's trying to build?

**Comment by martindekov** [comment]
Hey Matias it was:
```
2019/04/20 20:45:37 Building awesome. Tar: 8K
unable to deploy function via buildshiprun: invalid status code 500 for awesome2019/04/20 20:46:03 unexpected status code: 200
2019/04/20 20:46:03 deploy error: awesome failed to be deployed via buildshiprun
```
But probably I was using cached version of that image as I deleted the deployment and re-deployed and it works fine now 👍

**Comment by alexellis** [comment]
How is this going overall chaps?

**Comment by martindekov** [comment]
I started the implementation for GitLab last week I intend to finish it today

**Comment by matipan** [comment]
Awesome! That's good to hear Martin.
I've completed the github and git tar functions. I'm still working on the
dashboard. I wanted to learn a bit of react before making any changes

**Comment by martindekov** [comment]
Hey @matipan I now get you, I had to face the issue before understanding it... The multiple namespaces for kubernetes for different branches for better isolation sounds like a great idea, but not sure how it will go with Swam users and branch tag sha naming is the logical step how am I supposed to see functions from different branches otherwise. Sorry in the beginning I misunderstood the proposals. Otherwise above is the opened GitLab PR ^ you can check it out.

**Comment by matipan** [comment]
No problem @martindekov :smile:. Glad you like the idea, for now I'm going to change the format of the image tag. When we make the changes to ofc-bootstrap we'll discuss how or if we'll add that feature.

Today I'll check out your PR and try to upload mine :+1: 

Good stuff!

**Comment by matipan** [comment]
The dashboard is done, with this I've finished the implementation. I added a new label for the functions deployment called `com.openfaas.cloud.git-branch` that will have the branch that was used to build that function. This label is also used in the dashboard when displaying the link to the repository's commits.
I'll upload a PR as soon as I can figure out why the `gofmt` command is failing when building `buildshiprun`.
A few screenshots of the new functionality:
![Screen Shot 2019-04-23 at 21 17 30](https://user-images.githubusercontent.com/8126891/56624891-27d10e00-6611-11e9-80ac-b8258fc78de4.png)
![Screen Shot 2019-04-23 at 21 41 27](https://user-images.githubusercontent.com/8126891/56624899-30294900-6611-11e9-86a4-5f76b5864d64.png)
![Screen Shot 2019-04-23 at 21 41 57](https://user-images.githubusercontent.com/8126891/56624900-30294900-6611-11e9-8a36-5b8a10fcbd06.png)

This can be tested if you use the following images:
* `matipan/buildshiprun:buildBranch`
* `matipan/of-git-tar:buildBranch`
* `matipan/github-push:buildBranch`
* `matipan/system-dashboard:buildBranch`

**Comment by matipan** [comment]
@martindekov @alexellis [Here is the PR](https://github.com/openfaas/openfaas-cloud/pull/441) for all of the above

**Comment by matipan** [comment]
This was a part of the [0.8.11 release](https://github.com/openfaas/openfaas-cloud/releases/tag/0.8.11). @sachin-dhamane do you want to test it out so that we can close this?

**Comment by matipan** [comment]
BTW ofc-bootstrap will eventually support this: https://github.com/openfaas-incubator/ofc-bootstrap/issues/104

**Comment by alexellis** [comment]
Hi all, is there anything else outstanding or needed for this?

Thanks,

Alex

**Comment by sachin-dhamane** [comment]
> This was a part of the [0.8.11 release](https://github.com/openfaas/openfaas-cloud/releases/tag/0.8.11). @sachin-dhamane do you want to test it out so that we can close this?

Yes! I'll test this weekend and confirm.
