### ISSUE TITLE
UI issue: icons don't scale with the page in Safari

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#451]
The icon to log out and for GitHub should scale as I scale the page bigger or smaller.

![Screenshot 2019-05-08 at 18 04 22](https://user-images.githubusercontent.com/6358735/57393811-cf2a7500-71bb-11e9-833c-3b705cfec159.png)

**Comment by alexellis** [comment]
This should be a simple fix, the code lives at: https://github.com/openfaas/openfaas-cloud/tree/master/dashboard/client

**Comment by alexellis** [comment]
Note: I observed this with Safari on Mac, but Chrome on Mac did scale correctly.

**Comment by Waterdrips** [comment]
@alexellis I cant replicate this on Mac OS X (10.14.5) on Firefox (67.0.1), Safari (12.1.1) or Chrome (74.0.3729.169)

**Comment by Waterdrips** [comment]
/ assign me

**Comment by Waterdrips** [comment]
@alexellis this looks like a safairi bug  from 2018! (see links)

https://github.com/FortAwesome/Font-Awesome/issues/13032  
https://openradar.appspot.com/radar?id=5024734567727104

I could try and hack the app to make it work for safari users but im not super confident in my css abilities!
