### ISSUE TITLE
Dashboard gets stuck when injecting Linkerd2

### ISSUE THREAD

**Issue by matipan** [openfaas/openfaas-cloud#460]
When we inject the linkerd2 proxy to the dashboard it gets stuck loading the list of the functions. This is due to how the linkerd2 proxy works(in-depth explanation below).

## Expected Behaviour

The dashboard should list the functions of the user that is being requested.

## Current Behaviour

It shows the loading icon forever.

## Possible Solution

This is happening due to how we proxy the HTTP headers on the `dashboard/api/` endpoint and how linkerd2 proxies http requests. When the dashboard receives an HTTP the headers look something like this:
```
{
  "host": "system-dashboard.openfaas-fn.svc.cluster.local:8080",
  "user-agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0",
  "accept": "application/json, text/plain, */*",
  "accept-encoding": "gzip, deflate,br",
  "accept-language": "en-US,en;q=0.5",
  "cache-control": "max-age=0",
  "cookie": "openfaas_cloud_token=redacted",
  "if-none-match": "W/\"335-7KrTIYzvEQn5+vFDhsofmEfx2zk\"",
  "l5d-dst-canonical": "system-dashboard.openfaas-fn.svc.cluster.local:8080",
  "referer": "https://system.openfaas.matiaspan.me/dashboard/matipan",
  "x-call-id": "d7eac6b9-ef9e-4ce4-b486-53ea914ef228",
  "x-forwarded-for": "127.0.0.1",
  "x-forwarded-host": "system.openfaas.matiaspan.me",
  "x-forwarded-port": "443",
  "x-forwarded-proto": "https",
  "x-original-uri": "/dashboard/api/list-functions?user=matipan",
  "x-real-ip": "127.0.0.1",
  "x-request-id": "e4aa9191c8e0207d4deefe22175da380",
  "x-scheme": "https",
  "x-start-time": "1558447816502446737"
}
```

Note that the `host` is set to the dashboard's service name. The problem is that the linkerd proxy uses the host header as host for the HTTP request that it's proxying. For example, if we request the following path: `/dashboard/api/list-functions?user=matipan`, the dashboard will build a request that it's trying to go to `http://gateway.openfaas:8080/function/list-functions?user=matipan`, but since we have the `host` header set to `system-dashboard.openfaas-fn.svc.cluster.local:8080` the final HTTP request that linkerd will make is the following:
```
DBUG [ 62.724746s] 10.4.2.47:8080 linkerd2_proxy::proxy::http::client client request:
  method=GET
  uri=http://system-dashboard.openfaas-fn.svc.cluster.local:8080/function/list-functions?user=matipan
  version=HTTP/1.1
  headers={
  "host": "system-dashboard.openfaas-fn.svc.cluster.local:8080",
  "user-agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0",
  "accept": "application/json, text/plain, */*",
  "accept-encoding": "gzip, deflate, br",
  "accept-language": "en-US,en;q=0.5",
  "cache-control": "max-age=0",
  "cookie": "openfaas_cloud_token=redacted",
  "if-none-match": "W/\"f0f-2ZI1YcAaKP0fB6TWwcUrsrR21KM\"",
  "l5d-dst-canonical": "system-dashboard.openfaas-fn.svc.cluster.local:8080",
  "referer": "https://system.openfaas.matiaspan.me/dashboard/matipan",
  "x-call-id": "1266604f-b8a0-4de3-9dda-c4b7bb43baee",
  "x-forwarded-for": "127.0.0.1",
  "x-forwarded-host": "system.openfaas.matiaspan.me",
  "x-forwarded-port": "443",
  "x-forwarded-proto": "https",
  "x-original-uri": "/dashboard/api/list-functions?user=matipan",
  "x-real-ip": "127.0.0.1",
  "x-request-id": "7f07fa0c752c6e6a9392793ffdd1bc2a",
  "x-scheme": "https",
  "x-start-time": "1558448858972697442"
}
```

Note that it's going back to the dashboard instead of to the gateway.

The fix is to simply copy the incoming headers and set the `host` to the gateway's url.

## Steps to Reproduce (for bugs)

1. Inject linkerd to the dashboard
2. Access the dashboard for a particular user
3. Note that it gets stuck(inspect the network and you'll see a 304 response from the dashboard)

## Context

I'm trying to add linkerd2 to openfaas cloud, when we write a blog post for integrating this we need to be clear to the users about this issue. And ask them to update the dashboard(after we release this fix)

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ): 18.09.2

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?: FaaS-netes

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by matipan** [comment]
Derek assign: me

**Comment by matipan** [comment]
Derek add label: area/dashboard

**Comment by matipan** [comment]
Derek add label: area/kubernetes

**Comment by alexellis** [comment]
Please could you format the JSON snippet? I'm having trouble reading it on mobile.

**Comment by matipan** [comment]
Done :+1:
