### ISSUE TITLE
Feature: Add Annotations to git-tar

### ISSUE THREAD

**Issue by chriskolenko** [openfaas/openfaas-cloud#466]
Whitelisted Annotations was added to buildshiprun but git-tar doesn't marshal the Annotations in the http request.

## Expected Behaviour
buildshiprun should be receive a request with Http_Annotations populated in the ENV

## Current Behaviour
Http_Annotations doesn't exist

## Possible Solution
Copy and paste Labels implementation for Annotations
https://github.com/openfaas/openfaas-cloud/blob/master/git-tar/function/ops.go#L409

## Steps to Reproduce (for bugs)
Add annotations to stack.yml and commit something.

## Context
This is needed for event connector pattern

## Your Environment
N/A

**Comment by alexellis** [comment]
Did you want to work on this?

**Comment by alexellis** [comment]
Derek close: released
