### ISSUE TITLE
handle installation and remove event in git-event

### ISSUE THREAD

**Issue by s8sg** [openfaas/openfaas-cloud#47]
Use `installation` and `remove` event from `github-app` to deploy and remove functions from the openfaas-cloud

**Current behaviour:** 
Currently only commit status event are handled. 

**Expected behaviour:** 
We can handle `installation` and `remove` event in `git event`

> Deploy an application using `openfaas-cloud` when a `installation` event is received
> Remove an application using `openfaas-cloud` when a `remove ` event is received

**Comment by martindekov** [comment]
Is someone currently working on this?

**Comment by alexellis** [comment]
Not to my knowledge.

**Comment by martindekov** [comment]
I already started to research the API. If the change is not ASAP change can i take the issue?

**Comment by martindekov** [comment]
I think in two or three days I will be ready with the change. Need time to check the API and how the code uses other existing functions.And I need to learn how to test the cloud efficiently so mainly my time will go in that direction.

**Comment by alexellis** [comment]
OK so can you summarise the discussion we had on Slack? I think you said github-event is already doing the work needed?

**Comment by martindekov** [comment]
Sure currently installation alone does not provide enough info for build and deploy, but it provides enough for the garbage-collect on application removal which was already done.

**Comment by martindekov** [comment]
Derek close: Discussed that the API does not provide enough information for the function to be built unless we have another API call and that the current implementation for how you "install" works. Garbage collect is supported on removal event.
