### ISSUE TITLE
Issue with deleting a repo

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#472]
## Expected Behaviour

Issue with deleting a repo should trigger garbage collection.

## Current Behaviour

The customer is being read as "" by reading the wrong field.

The GitHub app showed:
```
Customer:  not found in CUSTOMERS file via https://raw.githubusercontent.com/openfaas/openfaas-cloud/master/CUSTOMERS
```

## Possible Solution

Add a code-path to read the customer from the `installation_repositories` event.

```json
{
  "action": "removed",
  "installation": {
    "account": {
      "login": "alexellis",
```

## Steps to Reproduce (for bugs)

1. Create repo
2. Push code and get function in dashboard
3. Remove the repo
4. Function(s) don't go

## Context

A user Tomasz Miklas reported this on the community cluster

**Comment by alexellis** [comment]
@martindekov  @matipan - please can we check how this works in the GitLab world?

**Comment by martindekov** [comment]
As I added a comment I remember discussing that the info in the hook was not enough If I find the discussion I will refer it here
