### ISSUE TITLE
Allow openfaas healthcheck annotations

### ISSUE THREAD

**Issue by matipan** [openfaas/openfaas-cloud#488]
Currently we only allow the user to set the `topic` annotation in their functions. Since we now support custom health checks it would be good if we add those to the array.

## Expected Behaviour

Allow me to set custom health checks for the functions that I deploy via OpenFaaS Cloud.

## Current Behaviour

 Any annotation that is not `topic` is ignored.

## Possible Solution

Simply add the following two values `"com.openfaas.health.http.path","com.openfaas.health.http.initialDelay"` to the white list array. We could feature toggle it if necessary.

Here's the new annotation name that we need to whitelist: https://docs.openfaas.com/reference/workloads/#custom-http-health-check

Update this code:

https://github.com/openfaas/openfaas-cloud/blob/0734d548b3d09c4b1da1a48790c32d9be9e63325/buildshiprun/handler.go#L212

Add a test / case here:
https://github.com/openfaas/openfaas-cloud/blob/0734d548b3d09c4b1da1a48790c32d9be9e63325/buildshiprun/handler_test.go#L421

## Steps to Reproduce (for bugs)

1. On an existing openfaas cloud installation, create a function with the health check annotations
2. Inspect the deployment and notice that it has the default liveness/readiness probes
3.
4.

## Context

I was creating a function for deploying static sites with hugo. Hugo does not have a `/_/health`, so my pod was in a CrashLoopBackOff, once I modified the handler to allow those annotations it worked great 😄 

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by matipan** [comment]
Derek assign: me

**Comment by alexellis** [comment]
Sounds fine. Can you also do a workaround by creating that static file path?

**Comment by alexellis** [comment]
@matipan would that also work?

**Comment by matipan** [comment]
> Sounds fine. Can you also do a workaround by creating that static file path?

Sorry, I'm not sure what you meant. What static file path are you referring to?

**Comment by alexellis** [comment]
OpenFaaS looks at what path by default? Create that path in your Hugo template?

**Comment by matipan** [comment]
I think that would work. I would have to change the template a bit. Currently I was using the `hugo server` command. Perhaps I could build a small HTTP server that serves content from the `public` directory that hugo builds, I could use nginx but I think for this use case having something more lightweight is better. It could be generic enough so that building a template for jekyll would be easier using that same binary

**Comment by alexellis** [comment]
I'll await a PR 👍

**Comment by alexellis** [comment]
Given that I've not heard back from @matipan since July, I'm opening this up to the community to take on.

Here's the new annotation name that we need to whitelist: https://docs.openfaas.com/reference/workloads/#custom-http-health-check

Update this code:

https://github.com/openfaas/openfaas-cloud/blob/0734d548b3d09c4b1da1a48790c32d9be9e63325/buildshiprun/handler.go#L212

Add a test / case here:
https://github.com/openfaas/openfaas-cloud/blob/0734d548b3d09c4b1da1a48790c32d9be9e63325/buildshiprun/handler_test.go#L421
