### ISSUE TITLE
Update GitHub statuses API for commits

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#5]
We can update GitHub statuses API for commits and give feedback on whether a push / deployment succeeded or failed.

- This needs an extended OAuth permission for the GitHub App to write commit statuses - everyone will have to accept the new permissions to update commit statuses on their repos

- The Golang GitHub library used with Derek should be able to do this - vendor it if it's not already there

- We have to authenticate to the GitHub API to write a status - use the [Derek code that](https://github.com/alexellis/derek/tree/master/auth)

- We have to use a cert/pem from the GitHub App - use a secret to store it on Docker/Kubernetes and updated the README with instructions on how to use it

- We need a description for events to go back to GitHub - keep this brief right now just pass or fail will do

- We have to extend the JSON "push message" structs to accept the installation ID - this is needed so we can authenticate later into an "installation - i.e. a GitHub repo". See the [Derek package](https://github.com/alexellis/derek/tree/master/types) and vendor if needed.

I would suggest writing the status back via the final buildshiprun function (it will need the pem/cert secret attaching to it)

**Comment by iyovcheva** [comment]
Can take this

**Comment by iyovcheva** [comment]
I didn't have a look yet. Happy to work on this, but it's not on top of the priority list, so if someone
 wants to take it - feel free.

Please write a comment, so that we don't duplicate efforts.

**Comment by alexellis** [comment]
> t it's not on top of the priority list

For OpenFaaS Cloud to be useful this is definitely high priority. We need a way of providing feedback. I'll add a a label.

**Comment by s8sg** [comment]
I'll be happy to work on it :)

**Comment by alexellis** [comment]
@s8sg thanks for working on this. I've added some more notes since this is going to require auth we have to pull in some new code. I'd suggest using the work from Derek - vendor it if you can.

**Comment by ericstoekl** [comment]
Derek close: PR is merged
