### ISSUE TITLE
Limit # of functions per repo

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#50]
An exhaustion attack on OpenFaaS Cloud could involve adding hundreds of functions to a stack file to exhaust resources and cause noise.

If these functions were deployed and created Pods then they would also cause the cluster to fill up.

We should look to add a config limit for how many functions are allows per repo/stack file.

I am thinking of a default limit of 5

**Comment by viveksyngh** [comment]
I will work on this one.

**Comment by viveksyngh** [comment]
@alexellis should we add that as an environment variable?. It would be helpful when someone has deployed OpenFaas cloud on their own infrastructure can adjust according to their needs.

**Comment by alexellis** [comment]
Yes all settings need to be configured in this way to be consistent.

**Comment by viveksyngh** [comment]
Derek add label: enhancement

**Comment by viveksyngh** [comment]
Derek assign: me
