### ISSUE TITLE
Uppercase username is invalid as part of sealed secret name

### ISSUE THREAD

**Issue by Qolzam** [openfaas/openfaas-cloud#502]
Account name with uppercase character are not valid to use as a sealed secret name and it cause issue when `import-secret` try to sealed a secret.

## Expected Behaviour

OFC should handle upper case user name. OFC lower the user name the time of importing and reading secret. 

## Current Behaviour

I got error when I created a secret with the name *qolzam-slack-token* :
> http status code 400, error: secrets *Qolzam-slack-token* not found

Then I created a secret with the name *Qolzam-slack-token* and redeploy but I got error again:

>[failed to parse secrets, error : import-secrets returned unexpected status: exit status 255
hash for HMAC validated successfully for Qolzam
couldn’t create SealedSecret (Qolzam-slack-token) - error: SealedSecret.bitnami.com “Qolzam-slack-token” is invalid: metadata.name: Invalid value: “Qolzam-slack-token”: a DNS-1123 subdomain must consist of lower case alphanumeric characters, ‘-’ or ‘.’, and must start and end with an alphanumeric character (e.g. ‘example.com’, regex used for validation is ‘a-z0-9?(.a-z0-9?)*’)
## Possible Solution

To work around creating an Github org with lowercase character solved the issue.

But possible solution could be lower the `Owner` name in `buildshiprun` and `import-secrets` handlers.
When it is adding owner name to secret from function YAML in [buildshiprun handler](https://github.com/openfaas/openfaas-cloud/blob/master/buildshiprun/handler.go#L461).

When it’s reading from secret.yml file to import the secrets in [import-secrets handler](https://github.com/openfaas/openfaas-cloud/blob/master/import-secrets/handler.go#L70)

## Steps to Reproduce (for bugs)

1. Have an Github account/org with upper case name.
2. [Use faas-cli](https://docs.openfaas.com/openfaas-cloud/secrets/) to create a sealed secret and add secret name to *stack.yml*.
3. Commit and push to Github.
4. See the log status in Github.

## Context

 
I want to create a secret for my function.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.8.13

* Docker version `docker version` (e.g. Docker 17.0.05 ): 19.03.1

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS): MacOS

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by Qolzam** [comment]
@alexellis What is your idea with lower the owner name for two part relate to importing secret that I mentioned. If you agree with the solution I can apply the changes to check the result.

**Comment by alexellis** [comment]
I'm fine with that approach. `faas-cli cloud seal` will also need to apply to lower.

**Comment by martindekov** [comment]
Thank you for the detailed explanation @Qolzam I will take a shot at this.

**Comment by martindekov** [comment]
Derek assign: me

**Comment by martindekov** [comment]
On a second though I would need to check the impact of the change. It is fairly easy to implement to lower in both places, but I am not sure of the impact and will need to test the change E2E to verify if to lower is the way to go, or we should augment logic if there is such, where we compare values etc. For the UI the approach was direct as in the URL your GitHub name is always with lower case.

**Comment by jonatasbaldin** [comment]
Hey @martindekov, I'll tackle this one.

I'll will search the code base and try to understand if case lowering is enough and doesn't break other things.

Is there a set of E2E tests that I can run locally, automatically or manually?

**Comment by alexellis** [comment]
You will need to deploy the whole thing. The easiest way to do that is to turn off outh and TLS. Bootstrap will take about 100 seconds. 

The incoming webhooks just make use of inlets.

**Comment by alexellis** [comment]
Having looked into this myself, I am fairly sure that you can go ahead with the solution proposed and it will work.

**Comment by martindekov** [comment]
I can help you test it, have spend the weekend to create private repo with my own configuration to ease the process of developing.

**Comment by martindekov** [comment]
Derek assign: jonatasbaldin

**Comment by jonatasbaldin** [comment]
I'm having problems deploying OFC locally, once I get that I'll keep working on this :)

**Comment by alexellis** [comment]
What do you use for your local environment?

**Comment by alexellis** [comment]
Is there a problem with networking or the bootstrap?

**Comment by jonatasbaldin** [comment]
Using Docker for Mac. I posted my errors at #openfaas-cloud in Slack, I think it's a better place to discuss the troubleshooting. Is that ok? Or should we talk here?

**Comment by jonatasbaldin** [comment]
Hi there!

I was trying to reproduce the error but I get this when I push a `stack.yml` with a secret:
```

**Comment by alexellis** [comment]
What are the logs of import-secrets?

**Comment by alexellis** [comment]
The namespace looks wrong there

**Comment by alexellis** [comment]
Try adding:

```
--namespace openfaas-fn
```

**Comment by alexellis** [comment]
```
2019/10/19 15:04:35 Out=hash for HMAC validated successfully for alexellis
couldn't get SealedSecret (alexellis-ofc-k3d) - error: sealedsecrets.bitnami.com "alexellis-ofc-k3d" is forbidden: User "system:serviceaccount:openfaas-fn:sealedsecrets-importer-rw" cannot get resource "sealedsecrets" in API group "bitnami.com" in the namespace "default"
```

Adding that worked for me:

```
2019/10/19 15:06:20 Forking fprocess.
2019/10/19 15:06:20 Query  
2019/10/19 15:06:20 Path  /
hash for HMAC validated successfully for alexellis
Imported SealedSecret: alexellis-ofc-k3d as new object
2019/10/19 15:06:20 Duration: 0.046695 seconds
```

**Comment by jonatasbaldin** [comment]
Shouldn't the namespace be that by default?

But anyway, added the namespace and still got the same error:
```
faas-cli cloud seal --name jonatasbaldin-my-secret --literal api-key=1234  --cert=./pub-cert.pem --namespace openfaas-fn
```

Logs from import-secrets:
```
2019-10-19T15:08:08Z import-secrets (import-secrets-7fbc88bdbb-zd2hx) 2019/10/19 15:08:08 Success=false, Error=exit status 255
2019-10-19T15:08:08Z import-secrets (import-secrets-7fbc88bdbb-zd2hx) 2019/10/19 15:08:08 Out=hash for HMAC validated successfully for jonatasbaldin
2019-10-19T15:08:08Z import-secrets (import-secrets-7fbc88bdbb-zd2hx) couldn't create SealedSecret (jonatasbaldin-my-secret) - error: the server could not find the requested resource (post sealedsecrets.bitnami.com)
2019-10-19T15:08:08Z import-secrets (import-secrets-7fbc88bdbb-zd2hx) ```

**Comment by alexellis** [comment]
Indeed, there appears to be a bug in the CLI introduced via the latest namespace changes.

https://github.com/openfaas/faas-cli/issues/708

It works for me when specifying the parameter with CLI 0.6.3.

If you don't have the CRD for SealedSecrets, delete the k3d cluster and start over, it should take < 1 min.

**Comment by jonatasbaldin** [comment]
Just rebuild the cluster before this operation and still didn't the CRD :( Where's the YAML file for that?

**Comment by jonatasbaldin** [comment]
Just added the controller by hand from the [bitnami release](https://github.com/bitnami-labs/sealed-secrets/releases/):

```
$ kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.9.2/controller.yaml
```

And it's building now.

Would this be a bug in the `ofc-bootstrap`?

**Comment by alexellis** [comment]
It sounds like your installation may have ran into an error, did you look at the logs?

Also how is it a bug if it works for me? Might be timings. 

https://github.com/openfaas-incubator/ofc-bootstrap/blob/master/scripts/install-sealedsecrets.sh

**Comment by jonatasbaldin** [comment]
Didn't get any error logs in the installation. Will retry later.

Well, a bug is when something doesn't work, specially when what's not working is flaky, right?

Anyway, here's what's happening now:
- Changed `buildshiprun` block from the line `461` to:
```golang
	for i := 0; i < len(info.Secrets); i++ {
		info.Secrets[i] = strings.ToLower(info.Owner) + "-" + info.Secrets[i]
	}
```

- Changed `import-secrets` block from the line `70` to:
```golang
	name := strings.ToLower(fmt.Sprintf("%s", userSecret.Metadata.Name))

	if strings.HasPrefix(name, strings.ToLower(event.owner)) == false {
		return fmt.Errorf("unable to bind a secret which does not start with owner name: %s", event.owner).Error()
	}
```

With these changes, this is what's happening:
- The SealedSecret is being created:
```
$ k get sealedsecrets.bitnami.com -n openfaas-fn  
NAME                            AGE
jonatasbaldin-my-secret         50m
uppercase-username-my-secret    30m
uppercase-username-my-secret2   8m46s   <- this is the one i'm testing now
```

- The logs from `import-secrets` indicates that the secret is being created:
```
$ faas logs import-secrets
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.
2019-10-19T16:00:50Z import-secrets (import-secrets-59477bb896-9rr5k) 2019/10/19 16:00:50 Forking fprocess.
2019-10-19T16:00:50Z import-secrets (import-secrets-59477bb896-9rr5k) 2019/10/19 16:00:50 Query  
2019-10-19T16:00:50Z import-secrets (import-secrets-59477bb896-9rr5k) 2019/10/19 16:00:50 Path  /
2019-10-19T16:00:50Z import-secrets (import-secrets-59477bb896-9rr5k) hash for HMAC validated successfully for Uppercase-username
2019-10-19T16:00:50Z import-secrets (import-secrets-59477bb896-9rr5k) Imported SealedSecret: uppercase-username-my-secret2 as new object
2019-10-19T16:00:50Z import-secrets (import-secrets-59477bb896-9rr5k) 2019/10/19 16:00:50 Duration: 0.094196 seconds
```

- But no secret is actually being created:
```
$ k get secrets -n openfaas-fn                  
NAME                                    TYPE                                  DATA   AGE
basic-auth-password                     Opaque                                1      107m
...

# output doesn't show uppercase-username-my-secret2
```

- Then the deployment of the function fails because it can't find the secret, logs from `buildshiprun`:
```
2019-10-19T16:13:41Z buildshiprun (buildshiprun-56b449999b-hj28f) 2019/10/19 16:13:41 Forking fprocess.
2019-10-19T16:13:41Z buildshiprun (buildshiprun-56b449999b-hj28f) 2019/10/19 16:13:41 Query  
2019-10-19T16:13:41Z buildshiprun (buildshiprun-56b449999b-hj28f) 2019/10/19 16:13:41 Path  /
2019-10-19T16:13:50Z buildshiprun (buildshiprun-56b449999b-hj28f) 2019/10/19 16:13:50 Success=false, Error=exit status 1
2019-10-19T16:13:50Z buildshiprun (buildshiprun-56b449999b-hj28f) 2019/10/19 16:13:50 Out=2019/10/19 16:13:41 0 env-vars for goto
2019-10-19T16:13:50Z buildshiprun (buildshiprun-56b449999b-hj28f) 2019/10/19 16:13:41 0 env-vars for uppercase-username-goto
2019-10-19T16:13:50Z buildshiprun (buildshiprun-56b449999b-hj28f) 2019/10/19 16:13:48 Image build status: 200
2019-10-19T16:13:50Z buildshiprun (buildshiprun-56b449999b-hj28f) 2019/10/19 16:13:48 buildshiprun: image 'docker.io/jonatasbaldin/uppercase-username-ofc-test-goto:latest-master-5fef794'
2019-10-19T16:13:50Z buildshiprun (buildshiprun-56b449999b-hj28f) 2019/10/19 16:13:48 pipeline-log: status: 500
2019-10-19T16:13:50Z buildshiprun (buildshiprun-56b449999b-hj28f) 2019/10/19 16:13:48 Deploying docker.io/jonatasbaldin/uppercase-username-ofc-test-goto:latest-master-5fef794 as uppercase-username-goto
2019-10-19T16:13:50Z buildshiprun (buildshiprun-56b449999b-hj28f) functionExists status: 200 OK
2019-10-19T16:13:50Z buildshiprun (buildshiprun-56b449999b-hj28f) Deploying: docker.io/jonatasbaldin/uppercase-username-ofc-test-goto:latest-master-5fef794 as uppercase-username-goto
2019-10-19T16:13:50Z buildshiprun (buildshiprun-56b449999b-hj28f) 2019/10/19 16:13:48 Deploy status [POST] - 400
2019-10-19T16:13:50Z buildshiprun (buildshiprun-56b449999b-hj28f) 2019/10/19 16:13:48 
2019-10-19T16:13:50Z buildshiprun (buildshiprun-56b449999b-hj28f) 2019/10/19 16:13:50 http status code 400, error: secrets "uppercase-username-my-secret2" not found
2019-10-19T16:13:50Z buildshiprun (buildshiprun-56b449999b-hj28f) 
```

I took a look around but the code is quite big, so maybe you have an idea on what's happening? My hunt is that, for some reason, the `import-secrets` is not doing its job but not throwing any errors for that.

**Comment by alexellis** [comment]
You need to use a lower-case username when you still the secret.

**Comment by jonatasbaldin** [comment]
It worked! Will open the PR ✨

**Comment by alexellis** [comment]
👍  it appears buildshiprun and import-secrets need a change.
