### ISSUE TITLE
[Feature request] ECR support - create repos in ECR API before push

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#504]
The OpenFaaS Cloud CI/CD pipeline creates Docker images in a remote registry and those image tags are dynamic. ECR doesn't support this behaviour in the same way as the Docker Hub or other registries we've used so far.

## Expected Behaviour

As an AWS user, I should be able to use [AWS ECR](https://docs.aws.amazon.com/AmazonECR/latest/userguide/what-is-ecr.html) for my images

## Current Behaviour

ECR won't work because an API call is required to create each image name, before it's pushed.

The Open Source Docker registry and the Docker Hub does not require this, but ECR is consistent with [Quay.io](https://quay.io) and potentially other registries like [sonatype Nexus](https://blog.sonatype.com/using-nexus-3-as-your-repository-part-3-docker-images).

## Possible Solution

The repo needs to be created *before* the build is carried out, which would mean adding code to `buildshiprun` around this line:

https://github.com/openfaas/openfaas-cloud/blob/master/buildshiprun/handler.go#L86

An initial working prototype may alter buildshiprun directly, but a more polished solution may deploy yet another OFC function, or exist in a separate generic library and be vendored in.

An AWS IAM role will be required.

@mhausenblas (AWS) was very helpful 🙏 and provided me with the following resources that I think help solve the problem:

* Go SDK for ECR -> https://godoc.org/github.com/aws/aws-sdk-go-v2/service/ecr#Client.CreateRepositoryRequest
* IAM -> https://docs.aws.amazon.com/AmazonECR/latest/userguide/ecr_managed_policies.html

Once added the code will need to accept a new access key ID and secret access key for the ECR API, this will also have to be inputted via [ofc-bootstrap](https://github.com/openfaas-incubator/ofc-bootstrap)

## Context

Customers on AWS tend to want to use ECR

If you want this, or want to help build it please comment 👇

**Comment by alexellis** [comment]
Here's the bad news.. the push token has to be renewed every 12 hours https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-basics.html

**Comment by burtonr** [comment]
FluxCD have created a registry package that manages the auth and handles the token refresh: https://github.com/fluxcd/flux/tree/master/registry
> courtesy of @stefanprodan :100:

**Comment by csakshaug** [comment]
This feature request same as #521 ?

**Comment by alexellis** [comment]
#521 is the PR and this is the tracking issue which can now be closed :+1:

**Comment by alexellis** [comment]
This is now available. Instructions will be made available via the ofc-bootstrap repo
