### ISSUE TITLE
Proposal: Add more useful metrics for functions 

### ISSUE THREAD

**Issue by viveksyngh** [openfaas/openfaas-cloud#51]
Add more useful metrics for functions like following:

     1.  Number of 2xx requests per second 
     2. Number of Non-2xx requests per seconds
     3. Distribution of response time for requests

**Comment by alexellis** [comment]
👍 LGTM - I think this needs raising upstream on openfaas/faas too

**Comment by alexellis** [comment]
We can get any metrics from Prometheus which are recorded - but the API Gateway doesn't have a way to expose these yet.

**Comment by viveksyngh** [comment]
These metrics can also be exposed through `/system/functions` endpoint of the gateway.

**Comment by alexellis** [comment]
I don't believe that endpoint currently provides the level of detail we want.

Can you raise an issue on the faas project please? This change would need to happen upstream.

cc @stefanprodan

**Comment by viveksyngh** [comment]
Yes. I will raise an issue with the faas project. @alexellis We want to expose RED metrics through the gateway right?

**Comment by viveksyngh** [comment]
I have raised this issue with faas repo. https://github.com/openfaas/faas/issues/703

**Comment by viveksyngh** [comment]
Derek add label: proposal
