### ISSUE TITLE
Docs: Update README with upgrade instructions

### ISSUE THREAD

**Issue by blaisep** [openfaas/openfaas-cloud#519]
I will add a few instructions on how to upgrade your OFC installation.

## Expected Behaviour

After installation and customization, it's likely that the upstream version will change and it's not clear to the newcomer what steps they should take.

## Current Behaviour

The current installation docs don't include any instructions for updating.

## Steps to Reproduce (for bugs)

1. Read https://github.com/openfaas/openfaas-cloud/tree/master/docs#openfaas-cloud-installation-guide
2. Note the absence of upgrade instructions.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
CLI:  (via home-brew OS X)
 commit:  5ff1504047756f9ff2e0a10ae64803ab63df470a
 version: 0.9.3

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by blaisep** [comment]
I can submit a PR summarizing @tmiklas instructions.

**Comment by blaise-sumo** [comment]
Does this look about right?
```

### Update your installation

The versions are listed as tags in the repo: https://github.com/openfaas/openfaas-cloud/blob/$VERSION_TAG/stack.yml
For example, the stack file for containing the image list for version `0.9.12` is at  https://github.com/openfaas/openfaas-cloud/blob/0.9.12/stack.yml 

You can check the versions of your running images:
```
kubectl get pods -n openfaas-fn -o jsonpath="{.items[*].spec.containers[*].image}"
```


#### Follow these instructions to pick up the latest updates from upstream:

Edit your configuration file:
```
kubectl edit -n openfaas-fn deployment import-secrets 
```
and change the image version number to match the new values from the latest stack file.
```

**Comment by blaise-sumo** [comment]
...based on the discussion in the Slack channel, this ticket can be closed.

**Comment by Waterdrips** [comment]
/close
^
