### ISSUE TITLE
False error from register-image when image is present on ECR already

### ISSUE THREAD

**Issue by csakshaug** [openfaas/openfaas-cloud#539]
- The ECR implementation gives errors when the registry already exists (at least git-tar and register-image gives exit(1) and status code != 200)
- The name that `register_image` is using could have potential problem, today the name is `registry_url`/`github-org´-`function-name?`-`image`:`image-tag`-`repo-branch`-`repo-sha` on selected region. The problem is that when you have multiple clusters that have deployed the same stack you will suddenly start to share registry in pipelines. It could create some strange edge cases
- I think `register_image` should add a basic policy when the registry is created so we dont need to go back to fix this through other jobs

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* ofc-bootstrap
* AWS EKS

**Comment by alexellis** [comment]
Hi @csakshaug 

Is this still the case?

What is your suggested fix and how can I reproduce this? (perhaps you can fill out the Github Issue template?)

**Comment by csakshaug** [comment]
we can check soon

**Comment by Waterdrips** [comment]
I think this will still happen, the code is 
```
        log.Printf("Attempting to create repo: %s\n", image)

	output, err := client.CreateRepository(&repoReq)

	if err != nil {
		log.Printf("CreateRepository error: %s\n", err.Error())
		os.Exit(1)
	}
```

We should probably check if the repo exists before trying to create it? Or at the very least check the error and see if its an "already exists" ?

**Comment by alexellis** [comment]
Why is that? (Sorry if I'm missing something)

**Comment by Waterdrips** [comment]
```sh
2020/02/25 18:41:40 Forking fprocess.
2020/02/25 18:41:40 Query  
2020/02/25 18:41:40 Path  /
2020/02/25 18:41:40 Success=false, Error=exit status 1
2020/02/25 18:41:40 Out=2020/02/25 18:41:40 Attempting to create repo: default-cluster0/waterdrips-openfaas-cloud-functions-chatbot
2020/02/25 18:41:40 CreateRepository error: RepositoryAlreadyExistsException: The repository with name 'default-cluster0/waterdrips-openfaas-cloud-functions-chatbot' already exists in the registry with id '011634693103'
        status code: 400, request id: c7fb315b-3226-4c00-ba07-a91c81512263

```

I get this with the 2nd + deploys, it always tries to make the repo, even if it already exists. 

It always tries to create it, never checks if it already is there


in terms of this : 
>The name that register_image is using could have potenical problem, today the name is registry_url/github-org´-function-name?-image:image-tag-repo-branch-repo-sha` on selected region. The problem is that when you have multiple clusters that have deployed the same stack you will suddenly start to share registry in pipelines. It could create some strange edge cases

(in initial comment), We could doccument that a user can add `/some-namespace` after the repository `$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/` in the config file,

This is what iv done: `$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/default-cluster0` and as you can see from the event, this gets added to the registry name :)

**Comment by alexellis** [comment]
So can we return a 200 if "RepositoryAlreadyExistsException" is in the error text?
