### ISSUE TITLE
[Enhancement] Support multiple OFC apps per repository

### ISSUE THREAD

**Issue by Waterdrips** [openfaas/openfaas-cloud#540]
## Expected Behaviour

I would like to be able to have a repository built and deployed onto multiple OFC installations and see the build status set successfully for each app on each commit.

## Current Behaviour

The integration with multiple OFC installations is not great - It works but does not report back that the deployment was successful and you only see each "build" step in 1 app. (screenshot)
![image](https://user-images.githubusercontent.com/40488132/68408701-bd7f5580-017d-11ea-8eeb-95a0be655e85.png)

## Possible Solution

namespace the build steps to the cluster or something so they can appear under both apps

## Steps to Reproduce (for bugs)

1. Add multiple OFC integrations to a repository
2. Trigger a build

## Context

commits always sit in pending status and dont succeed.

## Your Environment

OFC Community and OFC personal, through Github integration

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
What is the usecase for this?

**Comment by Waterdrips** [comment]
Clusters in different regions, multiple clusters using different build branches (staging, master, dev?)
