### ISSUE TITLE
[Proposal] Add links to any Organisations a user is entitled to view 

### ISSUE THREAD

**Issue by Waterdrips** [openfaas/openfaas-cloud#548]
A user that has been added to am organisation has the ability to view the functions and dashboard for that organisation.
We should provide a list of links to those organisations on a users's dashboard for easy navigation

## Expected Behaviour

User can see links to all organisations and their personal dashboard.
## Current Behaviour

No links, user has to manually navigate
## Possible Solution

the organisations exist on the user's token claims, and also in the front end. We can create links to the dashboards of those organisations

**Comment by alexellis** [comment]
This sounds like a great precursor to the more elaborate filtering feature v
