### ISSUE TITLE
Update function images with release (#551 breaking change not in  0.12.0 dashboard)

### ISSUE THREAD

**Issue by brandonkal** [openfaas/openfaas-cloud#573]
I expect updated function docker images to be published with each release of openfaas-cloud.

In this particular case, [this line](https://github.com/openfaas/openfaas-cloud/blob/3b2fef0a7dc1e1be07005893360a131a31a1cef0/dashboard/stack.yml#L9) was not updated to reflect the changes before 0.12.0 was published.

## Expected Behaviour
It should be possible for a user to deploy OpenFaaS cloud without building docker images. If this project publishes updated versions of docker images, users can use:
```
faas deploy --read-template=false
```
on the stack yaml without having to completely clone and build this repository. This greatly simplifies the deploy process (ofc-bootstrap may wish to use this approach as well).

## Current Behaviour
A breaking change was made (renaming a function) and the project as a whole was published under a new version without updating the function images. This meant that the javascript was expecting to see a "system-metrics" function that did not exist, as it is not current.

## Possible Solution
1. Tests should be added to ensure that openfaas-cloud can be deployed without building all the functions.
2. Procedures should be put in place so that an automated version bump and publish of modified docker images is complete before an openfaas-cloud release is published.

**Comment by alexellis** [comment]
Releases are coordinated and tested with ofc-bootstrap, please only use this tool and the pinned version as stable. 

Thanks for your interest.

If you want to contribute tests you're more than welcome to.

**Comment by alexellis** [comment]
As for the YAML file definition please raise a specific issue stating which image you believe to be missing and we'll get it built for you after Christmas.

**Comment by alexellis** [comment]
cc @Waterdrips

**Comment by alexellis** [comment]
Possibly related: https://github.com/openfaas/openfaas-cloud/pull/555

**Comment by brandonkal** [comment]
Yes, Merry Christmas! Naturally I don't expect a rush here. Just wanted to make a note before forgetting.

The specific issue is that the dashboard docker image should be published to match what is in this repo.

**Comment by alexellis** [comment]
Perhaps this could have been better handled via Slack and a simple message in #openfaas-cloud asking for the image to be pushed? 

What is the purpose of `faas deploy --read-template=false`?

**Comment by alexellis** [comment]
(Given that it's Christmas Day and I didn't expect people to be logging GitHub issues today, I'd suggest you try 0.11.11 of openfaas-cloud, I've pinned that version in ofc-bootstrap).

**Comment by alexellis** [comment]
![0-7-2-issue](https://user-images.githubusercontent.com/6358735/71444803-142ff700-270c-11ea-81d6-02d3c48ab189.png)

That version of dashboard appears to have other issues.
