### ISSUE TITLE
Community cluster Github app: Don't fail if not on master

### ISSUE THREAD

**Issue by mrsimpson** [openfaas/openfaas-cloud#583]
## Expected Behaviour
The [community cluster Github App](https://github.com/apps/openfaas-cloud-community-cluster) should not report failure if not on `master`

## Current Behaviour

Currently, the app exits with an error code if it runs on branches other than master. This leads to PRs not being able to be judged with respect to quality easily since the overall status will be `failed`

## Possible Solution

Ideally, it should build but not deploy if not on master
Quick win but also acceptable would be if the app completes with no-error without doing anything.

## Steps to Reproduce (for bugs)

1. Add the app to a repo
2. Create a branch and a PR
3. See it fail

<img width="934" alt="Bildschirmfoto 2020-02-05 um 10 35 06" src="https://user-images.githubusercontent.com/17176678/73833972-2b81fa00-480b-11ea-90e0-f0a8f2a2113d.png">

## Your Environment
Github + OpenFaas cloud community cluster

**Comment by alexellis** [comment]
So we have to give feedback to the user, and when we give no feedback people open issues saying "openfaas cloud isn't working"

What would you suggest here? cc @Waterdrips @martindekov

**Comment by martindekov** [comment]
https://github.com/openfaas/openfaas-cloud/blob/8c916971c5a9d40f73f7607bae7e454406ed32be/gitlab-push/handler.go#L227
This is for GitLab^ similar approach is taken for GitHub. We can split the logic here by passing boolean down the pipeline to only build the branch and not deploy it if it is not the `buildBranch`.

**Comment by martindekov** [comment]
Instead of throwing an exception and reporting failure ^.

**Comment by Waterdrips** [comment]
I thought we had a discussion the other day about the fact that if we implement build-time secrets we might not want random branches/PRs building, they could be written to expose those secrets (im thinking the new node tests functionality)

**Comment by martindekov** [comment]
Can't we just disable the build if the configuration contains build-time secrets and report is as error like:
```
Error: your image has build-time secrets. Refusing to build branch.
```
? I suppose we would declare the build time secrets in the `stack.yml` file?

**Comment by martindekov** [comment]
We can fail at `git-tar`. Here we parse the `stack.yml`:
https://github.com/openfaas/openfaas-cloud/blob/7d7edc46ed1f2f570c62089b5524e5a40b032b95/git-tar/function/handler.go#L117

**Comment by martindekov** [comment]
If we agree on the solution I can start working on it 👍

**Comment by Waterdrips** [comment]
I'm not sure I would want this in. Definitely not on my personal clusters. 

If this is implemented please put it behind a flag so it can be disabled. I'd probably default it to off too

**Comment by alexellis** [comment]
@Waterdrips how are you understanding the proposed solution? I think we maybe just return an ok / passed status with the same error message.

**Comment by Waterdrips** [comment]
My understanding of the proposal is:
Build every commit.

Some teams have lots of devs working on lots of branches for a repository, I wouldn't want to use compute power on building all of these commits because that leaves less compute for production workloads.

Possibly on a dev/stage type cluster I might want everything building (but only deploying the specified branch)

Is this not what is being proposed?

**Comment by martindekov** [comment]
Yeah Alistair you are right that's what is proposed. So should we add this as enable disable feature. Or not adding it at all ?

**Comment by mrsimpson** [comment]
>  I wouldn't want to use compute power on building all of these commits

We‘re talking about compute power of the CI here, right? Or is there any clusters-side task involved in building?
Frankly, I as a Github user without private runners don’t care about Microsoft’s compute investment much.

**Comment by alexellis** [comment]
I am not sure I follow @mrsimpson?

**Comment by mrsimpson** [comment]
😂 I am not sure I’m following either. 
My original problem was that the GitHub app for the Community cluster reports an error if not running for `master`. 
I want the build in CI in order to verify the image to be deployed is tested and ok. 

Now comes the area of assumptions:

- I expected the build to basically be a dicker build, running locally on the thread performing the build, locally. I assumed this since I configured Lucas Roesler‘s github action to perform a build and supplied no credentials for an OpenFaaS cluster and it builds, returning ok. 
- Now, a lot has been discussed which I didn’t fully get, finally @waterdrips stating „ I wouldn't want to use compute power on building all of these commits because that leaves less compute for production workloads“. This was confusing to me since I don’t see how a CI task affect production workloads. That’s all. 

Yes, I would like to be able to have a build for each commit or at least commit with a PR. I expect the build to fail in unit test failure or the docket build fail due to other reason. 

Now, I’ll keep my fingers shut ;-)

**Comment by Waterdrips** [comment]
The build is all done in-cluster and we just report back status

**Comment by mrsimpson** [comment]
Ahh, now that’s clear. 
What’s the quakitative advantage compared to just building the image „locally“?

**Comment by Waterdrips** [comment]
There is no "locally" there is no CI linked to your personal repo and the OpenFaaS Cloud installation has no way of creating CI for a repository on the VCS provider, we support both guthub and gitlab.

**Comment by mrsimpson** [comment]
I learned from @Waterdrips on the openfaas slack that another one of my expectations was wrong: I thought the app was like a set of actions running as part of the pipeline. Now I understood that by adding the app you basically add a receiver for the push event, like a webhook receiver. Thus, the build can not be triggered by the app as part of the CI process, but triggers a process in the cluster which pulls and builds, reporting back the state.

Given this, I'd kind-of re-frame the scope of the Github app: The Github app should only be responsible for making the function run in the community cluster, nothing more (pure CD). 
Each user  of the community cluster should ensure CI by creating an own pipeline, e. g. by adding [@LucasRoesler 's Github actions](https://github.com/LucasRoesler/openfaas-action) or by installing `faas-cli` and invoking `build`.
Then, the OpenFaas Community cluster would expectedly *ignore* all branches except `master` (not failing it, but simply returning "ok" as step result).

WDYT?

**Comment by mrsimpson** [comment]
I was free to open a [PR on the docs](https://github.com/openfaas/community-cluster/pull/2) as per how I'd have better understood the workflow. I thought this was more merge-able compared to write "you should adapt the guide like...".

**Comment by martindekov** [comment]
I believe this should be there as a feature behind a flag. I can think of multiple use cases where we would like to have more than 1 branch building not only when change is merged. I don't see why we we would not like this as feature. We can provide the users with the option and they can opt in or out when deploying the solution on their environment.

**Comment by martindekov** [comment]
I personally would like to build branches from PRs/MRs to verify that at least they build before merging. Eventually we can even extend to deploy in dev namespace when namespaces are available in this repo for testing.

**Comment by Waterdrips** [comment]
yeh, put it behind a flag, off by default?

**Comment by Waterdrips** [comment]
> Yeah Alistair you are right that's what is proposed. So should we add this as enable disable feature. Or not adding it at all ?

@martindekov I missed this comment. I think we should put it in behind a flag

**Comment by alexellis** [comment]
This has been released and will be available on the community cluster soon.
