### ISSUE TITLE
Bump Kubernetes client version for import-secrets

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#594]
## Task

Bump up the Kubernetes client version for import-secrets, ideally to 1.17

https://github.com/openfaas/openfaas-cloud/tree/master/import-secrets

Good first issue - feel free to ask questions. e2e testing will be required with any PR and don't convert to Go modules at this time.

The import-secrets function imports SealedSecrets from a user's GitHub repository into the cluster, where the controller then attaches them as plain secrets.

**Comment by heyts** [comment]
Hi @alexellis I might be able to work on this tonight / tomorrow if no one has a PR faster.

**Comment by alexellis** [comment]
Sounds good.
