### ISSUE TITLE
Github event not working

### ISSUE THREAD

**Issue by TheYkk** [openfaas/openfaas-cloud#601]
>$ kubectl logs -n openfaas-fn deploy/system-github-event
```
Error while un-marshaling customers: invalid character 'p' looking for beginning of value, value: payload=%7B%22ref%22%3A%22
```
I have fresh install with ofc bootstrap.I had  install github app but nothing seeing in commits page.
![image](https://user-images.githubusercontent.com/21688838/75810021-cc2bf100-5d9a-11ea-889e-24c2160c1fe7.png)

**Comment by alexellis** [comment]
Hi

I can see from the screenshot that you've misconfigured your GitHub App, please use the documentation or `ofc-bootstrap create-github-app` to create your app.

https://docs.openfaas.com/openfaas-cloud/self-hosted/github/

Feel free to use Slack for technical support requests like this.

Alex
