### ISSUE TITLE
Set edge-auth's cookie to use "Secure" (HTTPS only)

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#605]
Set edge-auth's cookie to use "Secure" (HTTPS only)

## Expected Behaviour

The most secure configuration would be for us to set the Secure: true flag for the cookie in edge-auth, this prevents the cookie from being used over a plaintext (HTTP) connection.

The downsides here are that nobody can test without setting up full TLS i.e. LetsEncrypt, which tends to be a pain for development.

I would like to see this behaviour behind a flag, so that folks can still work locally on OAuth features without LetsEncrypt.

## Current Behaviour

The HTTP Only variable means that the token can't be read from JavaScript, and we use HTTPS on customer and public environments, so this change won't make much difference to existing users, it's more belt-and-braces.

## Possible Solution

Update this code https://github.com/openfaas/openfaas-cloud/blob/6df6e79f2b69c0f6b57104f4b75d4dce5d8a0701/edge-auth/handlers/oauth2.go#L154

**But read the setting from the edge-auth configuration.**

**Comment by alexellis** [comment]
@Waterdrips I understand you may want to pick this up?

**Comment by Waterdrips** [comment]
/assign: me

Yep, just testing it
