### ISSUE TITLE
[Proposal] Add resource limits to Platform functions

### ISSUE THREAD

**Issue by Waterdrips** [openfaas/openfaas-cloud#614]
https://cloudblog.withgoogle.com/products/gcp/kubernetes-best-practices-resource-requests-and-limits/amp/

> While your Kubernetes cluster might work fine without setting resource requests and limits, you will start running into stability issues as your teams and projects grow. Adding requests and limits to your Pods and Namespaces only takes a little extra effort, and can save you from running into many headaches down the line!

It's best practice to set resource limits on kubernetes.

We should ensure all OpenFaaS Cloud functions (the platform ones) have resource limits set.

## Expected Behaviour

Resource limits set on OFC Functions (platform functions)
## Possible Solution

https://cloudblog.withgoogle.com/products/gcp/kubernetes-best-practices-resource-requests-and-limits/amp/

**Comment by martindekov** [comment]
I believe we have this as an option in the stack.yml. How much memory should we let the functions have by default ? WDYT?

**Comment by Waterdrips** [comment]
Stack should be done yes. I need to also check the services we deploy with yaml + the chart

**Comment by alexellis** [comment]
Here's the community cluster:

```
kubectl top pod -n openfaas-fn -l role=openfaas-system
NAME                                   CPU(cores)   MEMORY(bytes)   
buildshiprun-5d7d564454-jjf22          51m          5Mi             
function-logs-59dd45475c-nw824         1m           11Mi            
garbage-collect-599f9f666f-n66m5       55m          7Mi             
git-tar-56cc7b774f-wmxg2               31m          2Mi             
github-push-79f6b476fb-vrt5f           32m          7Mi             
github-status-dcd4db8c-lksth           28m          6Mi             
import-secrets-6c84946cc6-bst2g        37m          8Mi             
list-functions-65bfcc77c9-hp44b        33m          6Mi             
metrics-f9594844f-qxpx5                34m          2Mi             
pipeline-log-79d9547485-kzsgz          29m          7Mi             
system-dashboard-687bdf798f-c7lwt      50m          27Mi            
system-github-event-7c67f76dd8-vrrkf   29m          14Mi            
system-metrics-5bbcf49976-sszs5        27m          2Mi 
```

Let's set requests of 32Mi limit of 128Mi
For the dashboard request 64Mi limit 256Mi
No CPU limits, but CPU requests `50m`

**Comment by alexellis** [comment]
Check the edge auth and router components have the same set:

```
edge-auth-bc8fd68f9-7crtd            1m           8Mi             
edge-router-675954564f-p5dfm         1m           10Mi 
```

**Comment by alexellis** [comment]
Also update gitlab.yml and aws.yml

**Comment by martindekov** [comment]
Just saw you left comments will add the changes as per:
```
Let's set requests of 32Mi limit of 128Mi
For the dashboard request 64Mi limit 256Mi
No CPU limits, but CPU requests 50m
``` 
👍

**Comment by alexellis** [comment]
Thanks. We will await a PR to test out / review.
