### ISSUE TITLE
New OpenFaaS Cloud Release 

### ISSUE THREAD

**Issue by Waterdrips** [openfaas/openfaas-cloud#630]
It would be useful to cut a new release so our users using the `ofc-bootstrap` tool can be used to deploy OFC with the new secure_cookie flag to imporve security.

https://github.com/openfaas-incubator/ofc-bootstrap/issues/200 (the code is written, just needs a new ofc release.)

Also, might be worth seeing which of the open PRs here should be merged.
Looking at the list these seem ready:
* [x] #624 
* [ ] #622 
* [x] #612 
* [ ] #611 
* [x] #632 #633

**Comment by alexellis** [comment]
Release cut here -> https://github.com/openfaas/openfaas-cloud/releases/tag/0.13.9
