### ISSUE TITLE
buildkit complains about 'invalid reference format' for pipeline build.

### ISSUE THREAD

**Issue by peidong-hu** [openfaas/openfaas-cloud#644]
I have setup everything with self-hosted gitlab on aws and openfaas in eks by following this article, https://www.openfaas.com/blog/openfaas-cloud-gitlab/

Everything seems working well. I can trigger the build in openfaas through push code to gitlab.

But the buildkit always complains invalid reference format. screenshot below,
![image](https://user-images.githubusercontent.com/7647371/82718444-25077900-9c68-11ea-9661-a24023489bf8.png)

## Steps to Reproduce (for bugs)

1.  Follow this article deploy gitlab and openfaas cloud, https://www.openfaas.com/blog/openfaas-cloud-gitlab/
2. push the example project mentioned in above article
3. build started in openfaas
4. check the logs in of-builder pod, and of-buildkit container

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
Hi, I wonder if there's a misconfiguration somewhere? Can you share your init.yaml file?

Alex

**Comment by peidong-hu** [comment]
I ran the command 'ofc-bootstrap apply -f example.init.yaml -f gitlab-openfaas-kube.eco-perf.cloud.yaml' to deploy. two yaml files attached. (i have to rename them to .txt to be able to attach there.)
====================
[example.init.yaml.txt](https://github.com/openfaas/openfaas-cloud/files/4672242/example.init.yaml.txt)
[gitlab-openfaas-kube.eco-perf.cloud_forAlex.yaml.txt](https://github.com/openfaas/openfaas-cloud/files/4672243/gitlab-openfaas-kube.eco-perf.cloud_forAlex.yaml.txt)

**Comment by alexellis** [comment]
I can see `registry: docker.io/zhouyibhic/` in your base YAML file.

What kind of hosts or nodes are you running on? If you're using the Docker hub, then that's still working for us and I can't see why you'd have an error there. @Waterdrips may have some suggestions.

Can you share the following?

```
kubectl get deploy -o yaml -n openfaas-fn buildshiprun
```

**Comment by alexellis** [comment]
You may also want to check your authentication is correct using our troubleshooting guide. There are a number of steps you can run through.

https://docs.openfaas.com/openfaas-cloud/self-hosted/troubleshoot/

FYI if you need more hands-on help, you can also [book time with me directly via OpenFaaS Ltd](https://www.alexellis.io) to debug it with you over Zoom.

**Comment by peidong-hu** [comment]
I am running in aws eks.  attached is the buildshiprun yaml through command kubectl get deploy -o yaml
[buildshiprun.yaml.txt](https://github.com/openfaas/openfaas-cloud/files/4672298/buildshiprun.yaml.txt)

**Comment by peidong-hu** [comment]
Thanks Alex for the troubleshooting docs, I have successfully fixed the tls certificate issue by upgrading the cert-manager from 0.7 to the latest version 0.15 and creating aws access key credential secret. 

Now everything works well except the 'invalid reference format' error in the of-buildkit container which fails the build pipeline for the timezone-shift example app.

Anyone knows if there is a trace level log to enable in buildkit? I have enabled the debug level log, but it doesn't give much useful information to debug this issue.

**Comment by alexellis** [comment]
We haven't run into an issue like that, but @AkihiroSuda may be able to provide some input regarding the issue.

Can you exec into the git-tar deployment and save the contents of `/tmp` after the failed build? It should give you a build context that you can run with `docker build`.

Are any of your nodes running ARM64?

**Comment by peidong-hu** [comment]
This file content is kind of suspicious in com.openfaas.docker.config in tmp folder,
Openfaas seems prefixed my full name which has space in it in the docker image name? 
![image](https://user-images.githubusercontent.com/7647371/82969316-fefa1580-9f94-11ea-8a03-49d3d1945e54.png)

**Comment by peidong-hu** [comment]
So now I can confirm the full name field value in gitlab is really causing 2 problems here.
1) if there is space in the full name field, the invalid reference format error will appear in buildkit
2) if the full name field value doesn't match the gitlab login username, dashboard won't list the user's function. 

Once I have set the user full name same as login username in gitlab, both issues disappeared.

**Comment by peidong-hu** [comment]
The red circled field in gitlab user setting has to be gitlab login username.

![image](https://user-images.githubusercontent.com/7647371/82971054-644f0600-9f97-11ea-8dc3-c4b7f67cd239.png)

**Comment by peidong-hu** [comment]
So here is the final result of the build and stack.yaml content, it seems that openfaas has prefixed the image name with <<gitlab user full name>>-<<image name>>-<<image name>>:latest-master-commit

does everything looks correct?

![image](https://user-images.githubusercontent.com/7647371/82971541-8bf29e00-9f98-11ea-96d9-176a15a84d18.png)

![image](https://user-images.githubusercontent.com/7647371/82971567-9ca31400-9f98-11ea-91a1-e709d1d0773f.png)

**Comment by Waterdrips** [comment]
Im going to raise a couple of issues off the back of your investigation to tackle the following


 *   if there is space in the full name field, the invalid reference format error will appear in buildkit
*    if the full name field value doesn't match the gitlab login username, dashboard won't list the user's function.

**Comment by Waterdrips** [comment]
/close 

tracking in new issue
