### ISSUE TITLE
Support private insecure docker registry?

### ISSUE THREAD

**Issue by peidong-hu** [openfaas/openfaas-cloud#645]
HI,

this is more a question than reporting an issue. Does the openfaas cloud supports insecure private docker registry that access through http?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
Please could you direct all your technical support requests to the Slack community? Use the #openfaas-cloud channel. Thank you.
