### ISSUE TITLE
buildkit failed to solve with frontend dockerfile.v0

### ISSUE THREAD

**Issue by peidong-hu** [openfaas/openfaas-cloud#648]
Hi,

I received this error when building a go project in openfaas cloud,

time="2020-06-15T16:29:52Z" level=error msg="/moby.buildkit.v1.Control/Solve returned error: buildkit-runc did not terminate sucessfully\nexecutor failed running [/bin/sh -c test -z \"$(gofmt -l $(find . -type f -name '*.go' -not -path \"./vendor/*\" -not -path \"./function/vendor/*\"))\" || { echo \"Run \\\"gofmt -s -w\\\" on your Golang code\"; exit 1; }]\ngithub.com/moby/buildkit/solver/llbsolver/ops.(*execOp).Exec\n\t/src/solver/llbsolver/ops/exec.go:712\ngithub.com/moby/buildkit/solver.(*sharedOp).Exec.func1\n\t/src/solver/jobs.go:688\ngithub.com/moby/buildkit/util/flightcontrol.(*call).run\n\t/src/util/flightcontrol/flightcontrol.go:119\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:44\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337\ngithub.com/moby/buildkit/solver.(*edge).execOp\n\t/src/solver/edge.go:869\ngithub.com/moby/buildkit/solver/internal/pipe.NewWithFunction.func2\n\t/src/solver/internal/pipe/pipe.go:82\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337\nfailed to build LLB\ngithub.com/moby/buildkit/solver/llbsolver.(*llbBridge).Solve\n\t/src/solver/llbsolver/bridge.go:116\ngithub.com/moby/buildkit/frontend/gateway/forwarder.(*bridgeClient).Solve\n\t/src/frontend/gateway/forwarder/forward.go:44\ngithub.com/moby/buildkit/frontend/dockerfile/builder.Build.func3.1\n\t/src/frontend/dockerfile/builder/build.go:382\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/src/vendor/golang.org/x/sync/errgroup/errgroup.go:58\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337\nfailed to solve with frontend dockerfile.v0\ngithub.com/moby/buildkit/solver/llbsolver.(*llbBridge).Solve\n\t/src/solver/llbsolver/bridge.go:127\ngithub.com/moby/buildkit/solver/llbsolver.(*Solver).Solve\n\t/src/solver/llbsolver/solver.go:136\ngithub.com/moby/buildkit/control.(*Controller).Solve\n\t/src/control/control.go:276\ngithub.com/moby/buildkit/api/services/control._Control_Solve_Handler.func1\n\t/src/api/services/control/control.pb.go:1364\ngithub.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1\n\t/src/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:57\nmain.unaryInterceptor.func1\n\t/src/cmd/buildkitd/main.go:526\ngithub.com/moby/buildkit/api/services/control._Control_Solve_Handler\n\t/src/api/services/control/control.pb.go:1366\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/src/vendor/google.golang.org/grpc/server.go:972\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/src/vendor/google.golang.org/grpc/server.go:1252\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.1\n\t/src/vendor/google.golang.org/grpc/server.go:691\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337"

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
version: 0.12.4
* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker 18.6
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
AWS EKS k8s 1.14

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
Seems like the error was given to you. Fix the formatting of your go code. Run gofmt -s -w file.go

**Comment by alexellis** [comment]
Closing as not an issue
