### ISSUE TITLE
how to add dependencies

### ISSUE THREAD

**Issue by peidong-hu** [openfaas/openfaas-cloud#649]
Hi,

It looks like I need to do something to make openfaas go-middleware work with dependencies as I received the following error, 

have searched on internet, but can't find something relevant. 

How can I add the k8s.io packages into openfaas build?

Thanks,
Peidong
=================
v: 2020-06-15T20:39:11Z [build 10/13] WORKDIR /go/src/handler/function
v: 2020-06-15T20:39:11Z [build 10/13] WORKDIR /go/src/handler/function 0.04s
v: 2020-06-15T20:39:11Z [build 11/13] RUN go test ./... -cover
l: 2020-06-15T20:39:12Z handler.go:7:2: cannot find package "k8s.io/apimachinery/pkg/api/errors" in any of:
	/usr/local/go/src/k8s.io/apimachinery/pkg/api/errors (from $GOROOT)
	/go/src/k8s.io/apimachinery/pkg/api/errors (from $GOPATH)
handler.go:8:2: cannot find package "k8s.io/apimachinery/pkg/apis/meta/v1" in any of:
	/usr/local/go/src/k8s.io/apimachinery/pkg/apis/meta/v1 (from $GOROOT)
	/go/src/k8s.io/apimachinery/pkg/apis/meta/v1 (from $GOPATH)
handler.go:9:2: cannot find package "k8s.io/client-go/kubernetes" in any of:
	/usr/local/go/src/k8s.io/client-go/kubernetes (from $GOROOT)
	/go/src/k8s.io/client-go/kubernetes (from $GOPATH)
handler.go:10:2: cannot find package "k8s.io/client-go/tools/clientcmd" in any of:
	/usr/local/go/src/k8s.io/client-go/tools/clientcmd (from $GOROOT)
	/go/src/k8s.io/client-go/tools/clientcmd (from $GOPATH)

v: 2020-06-15T20:39:11Z [build 11/13] RUN go test ./... -cover 0.26s
2020/06/15 20:39:12 Unable to build image, check builder logs

**Comment by alexellis** [comment]
Hi @peidong-hu please can you follow our community guidelines and ask your questions on Slack. We don't do technical support through GitHub issues.

Just join the #openfaas-cloud channel and ask how to add a dependency with Go. You will also find the documentation covers this topic. 

Alex
