### ISSUE TITLE
After deployment, Github failed to send payload to domain

### ISSUE THREAD

**Issue by JasonPad19** [openfaas/openfaas-cloud#654]
After deployment on Azure Kubernetes Cluster & Container Registry, Github failed to send payload to domain

## Expected Behaviour
Github should send commit payload to domain

## Current Behaviour
Github ->Adavanced page shows the error. Certificate is valid for ingress.local not domain. 

![image](https://user-images.githubusercontent.com/52347372/86880668-22da7a80-c141-11ea-9c6c-fc9030f8b2cc.png)

Also, When accessing the url via browser, it shows invalid certificate.
![image](https://user-images.githubusercontent.com/52347372/86881251-130f6600-c142-11ea-8f65-e633ff8cea32.png)

## Possible Solution
NA

## Steps to Reproduce (for bugs)
NA

## Context
- After deployment, it shows this error.
- No OAuth enabled.
- Also, during deployment, there is an issue as below.
Plan loaded from: [example.init.yaml init.yaml]
Validating registry credentials fileerror with registry credentials file. Please ensure it has been created correctly

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):  faas-cli version (0.12.4)

* Docker version `docker version` (e.g. Docker 17.0.05 ): NA

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes Cluster on Azure

* Operating System and version (e.g. Linux, Windows, MacOS):
Azure Cloud Shell on Windows 10 Laptop

* Link to your project or a code example to reproduce issue: NA

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:
NA

**Comment by alexellis** [comment]
Hi @JasonPad19 please feel free to reach out for technical support on Slack in the #openfaas-cloud channel

You should ideally provide us there with your YAML files, feel free to obscure the credentials, but do to change domains. 

Alex
