### ISSUE TITLE
Invalid Reference Format - buildkit, names with whitespace (Gitlab)

### ISSUE THREAD

**Issue by Waterdrips** [openfaas/openfaas-cloud#657]
Gitlab integration is possibly using the `full name` field, which could be causing buildkit to append an invalid value (a space) into the ref field. 

I think also we are using a mismatch of fullname and username somewhere, as its been reported that:

```sh 
if the full name field value doesn't match the gitlab login username, dashboard won't list the user's function.
```
see this issue for context 
https://github.com/openfaas/openfaas-cloud/issues/644

## Expected Behaviour

A name with whitespace can be handled in the application 

## Current Behaviour

Buildkit ref has whitespace, which is causing some issues (https://github.com/openfaas/openfaas-cloud/issues/644)
## Steps to Reproduce (for bugs)

1. Gitlab name with whitespace
2. Try and deploy a function
3. Invalid ref format in buildkit
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
This is an expected error, there are some GitLab usernames which cannot be supported in a Kubernetes Pod name or Docker image name or tag.

**Comment by Waterdrips** [comment]
/close


> This is an expected error, there are some GitLab usernames which cannot be supported in a Kubernetes Pod name or Docker image name or tag.

ill close then. Thanks

**Comment by alexellis** [comment]
How was the issue discovered? Was it reported by a user?

There is a GitLab documentation page, so it would make sense to add a note there

**Comment by Waterdrips** [comment]
#644
