### ISSUE TITLE
Feature: support cloudflare integration

### ISSUE THREAD

**Issue by hazcod** [openfaas/openfaas-cloud#662]
It would be nice for users to be able to attach the [Cloudflare cloudflared](https://github.com/cloudflare/cloudflared) Argo Tunnel proxy in front of OpenFaaS functions and even the dashboard, so that everything is automatically protected against DoS, additionally free certificate management and possibly even a web authentication layer.

## Expected Behaviour
The ingress should be replaced or prepended with a cloudflared instance that sets up a reverse tunnel to Cloudflare (using a cloudflare token), that publishes the website on the Cloudflare edge.

## Current Behaviour
Proxy Cloudflare to our edge server, which allows anyone to bypass Cloudflare WAF/DoS.

Edit: perhaps rather something for https://github.com/openfaas-incubator/ingress-operator

**Comment by alexellis** [comment]
Hi, thanks for your interest. This is the repo for the open-source project for OpenFaaS Cloud, I am not sure what you are asking for us to do?

**Comment by hazcod** [comment]
Hi Alex, i'm relatively new to OpenFaas so might not be the right repo, but I was wondering where cloudflared would fit in the OpenFaaS picture. Sec, i'll hop on the Slack.

**Comment by alexellis** [comment]
We don't generally take support questions over Slack, so it might make sense to ask on Slack 👍 I'll close out this issue for now.
