### ISSUE TITLE
minor doc tidy

### ISSUE THREAD

**Issue by ainiml** [openfaas/openfaas-cloud#670]
The fix: https://github.com/TheShellLand/openfaas-cloud/commit/d1ca7b368c76bcf12ad255838b65ec5a61bea83f

**Comment by alexellis** [comment]
@ainiml if you feel this is worth your time, in raising a PR, feel free. I see that you are able to add a sign-off message so I don't mind.

Just change your name to a real name, not an alias or synonym

```
git config user.name "Full Name here"
git commit -s --amend
```

**Comment by ainiml** [comment]
done https://github.com/openfaas/openfaas-cloud/pull/671

**Comment by alexellis** [comment]
Merged, thanks. Do you use this project btw?
