### ISSUE TITLE
Audit meaningful data from functions

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#68]
We should audit meaningful data from functions such as:

* git-tar - what size tar-ball?
* buildshiprun - what size Docker image in the registry etc?

These are just ideas - if we have the data, let's audit it so we can learn how to operate the system.

@ericstoekl has a PR #38 - Eric please can you break it up into smaller pieces and raise as PRs?

Thanks,

Alex

**Comment by viveksyngh** [comment]
Derek add label: enhancement

**Comment by martindekov** [comment]
Derek close: I had PR adding audit also in #38 @ericstoekl added auditing in lots of places so I think this is outdated
