### ISSUE TITLE
Dashboard image missing bundled assets

### ISSUE THREAD

**Issue by wilsonianb** [openfaas/openfaas-cloud#695]
The GitHub action [build](https://github.com/openfaas/openfaas-cloud/blob/master/contrib/ci.sh) and [publish](https://github.com/openfaas/openfaas-cloud/blob/master/contrib/publish.sh) scripts are missing the dashboard's [bundle asset step](https://github.com/openfaas/openfaas-cloud/tree/master/dashboard#build-and-bundle-the-assets).

## Expected Behaviour
The [`publish` GitHub action](https://github.com/openfaas/openfaas-cloud/blob/master/.github/workflows/publish.yaml) should produce a working dashboard image.

## Current Behaviour

The published image has a missing `index.html` error when run.

## Possible Solution

Run `make build-dist` in [build](https://github.com/openfaas/openfaas-cloud/blob/master/contrib/ci.sh) and [publish](https://github.com/openfaas/openfaas-cloud/blob/master/contrib/publish.sh) scripts

## Steps to Reproduce (for bugs)

1. Run  [`publish` GitHub action](https://github.com/openfaas/openfaas-cloud/blob/master/.github/workflows/publish.yaml)
2. Use published dashboard image in openfaas cloud cluster
3. Attempt to access dashboard

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
Thanks for the note. This work is still in progress, so slack would be a better forum for feedback.
