### ISSUE TITLE
Link to GitHub app from dashboard

### ISSUE THREAD

**Issue by wilsonianb** [openfaas/openfaas-cloud#697]
Users of an OpenFaaS Cloud cluster currently need to obtain the link of the GitHub app out of band.
Linking to the app in the dashboard would make the [installation step](https://docs.openfaas.com/openfaas-cloud/user-guide/#install-the-github-app) easier.

## Expected Behaviour

Ofc users can find the GitHub app to install via the dashboard

## Current Behaviour

Link to app is obtained out of band

## Possible Solution

Repurpose the dashboard icon linking to the openfaas-cloud github repo
https://github.com/codius/openfaas-cloud/commit/d52554f0249ed37922d761b1e2ea27037e884e9e

## Steps to Reproduce (for bugs)

1. 

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by wilsonianb** [comment]
Ditto for the cluster [sealed secrets](https://docs.openfaas.com/openfaas-cloud/secrets/) public key.
It could be served and linked to in the dashboard: https://github.com/codius/openfaas-cloud/commit/8e8a7c51b988ea67bdbd344cf1657cdb7ab0e4bf

**Comment by alexellis** [comment]
I would accept a PR for this @wilsonianb 

Since SealedSecrets is always going to be installed, we could use a glyph icon for a key, and one for git or a laptop for the Git link.

You'll find a URL for GitLab already, but GitHub will need to be built up or inputted.

**Comment by alexellis** [comment]
There is actually a gitlab FA icon, that we could switch in depending on config: https://fontawesome.com/icons?d=gallery&q=git

<img width="627" alt="Screenshot 2020-12-01 at 09 14 48" src="https://user-images.githubusercontent.com/6358735/100720301-b09b5880-33b5-11eb-892d-4618646aa812.png">

And for a key icon -> https://fontawesome.com/icons/key?style=solid

It'd also be good to have roll-over text for both so that people can see what they are before clicking.

How are we doing to serve the key? by mounting it in the dashboard and returning over `/api/...`?

**Comment by wilsonianb** [comment]
I can submit a pr.
>How are we doing to serve the key? by mounting it in the dashboard and returning over /api/...?

I've just been putting the key in `/dashboard/dist` like the favicon.ico
https://github.com/codius/openfaas-cloud/commit/8e8a7c51b988ea67bdbd344cf1657cdb7ab0e4bf

**Comment by alexellis** [comment]
We should also update the blank state page to reference how to install the app / download the sealedsecret key

<img width="1150" alt="Screenshot 2020-12-01 at 18 23 00" src="https://user-images.githubusercontent.com/6358735/100780951-4957c580-3402-11eb-90b2-b25805edfc76.png">
