### ISSUE TITLE
system-metrics on the dashboard is showing 0

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#700]
system-metrics on the dashboard is showing 0

## Expected Behaviour

It should show the invocations for the function in question.

## Current Behaviour

It shows 0

## Possible Solution

Pass the namespace - as the gateway now records function metrics with a namespace, even if it's the default one.

![fws](https://user-images.githubusercontent.com/6358735/100670292-8ebeb900-3356-11eb-946b-82a3fe5d0ff9.png)

## Steps to Reproduce (for bugs)

1. Deploy with the latest gateway
2. Check your dashboard after invoking a function. The overview page will show correctly.

![overview](https://user-images.githubusercontent.com/6358735/100670425-ba41a380-3356-11eb-9f30-40fe39d0cc41.png)

![missing](https://user-images.githubusercontent.com/6358735/100670430-bca3fd80-3356-11eb-9ea0-5ae51f93c339.png)

**Comment by alexellis** [comment]
@brandonkal or @Waterdrips would you to take a look please?

**Comment by brandonkal** [comment]
Thanks for the ping. I'm repairing my laptop and will then migrate my dev environment to a new machine so I don't anticipate being able to look at this in the near term.

**Comment by Waterdrips** [comment]
/assign: me
Ill take a look at this

**Comment by alexellis** [comment]
There is actually a gitlab FA icon, that we could switch in depending on config: https://fontawesome.com/icons?d=gallery&q=git

<img width="627" alt="Screenshot 2020-12-01 at 09 14 48" src="https://user-images.githubusercontent.com/6358735/100720301-b09b5880-33b5-11eb-892d-4618646aa812.png">

And for a key icon -> https://fontawesome.com/icons/key?style=solid

It'd also be good to have roll-over text for both so that people can see what they are before clicking.

How are we doing to serve the key? by mounting it in the dashboard and returning over `/api/...`?
