### ISSUE TITLE
Enable HMAC for auth on the import-secrets function

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#78]
We should auth on the import-secrets function by using HMAC.

In the same way that we have a symmetric secret which the `gh-push` function validates, we should have a shared secret that git-tar uses to sign the import secret request. In this way import-secrets will only import a secret signed by the owner of the new symmetric key.

## Tasks

* Create new named secret in `openfaas-fn` namespace (document this)

> Note: I don't know whether we should re-use the existing value in `github_webhook_secret` or whether we should create a new named secret. This shouldn't really be an environmental variable anyway. 

* Bind secret to git-tar and import-secrets functions
* Update DEV instructions in /docs/
* Test and validate that secrets are only imported when signed

Use the existing library for HMAC signing / verification.

**Comment by viveksyngh** [comment]
I can work on this one.

**Comment by alexellis** [comment]
https://github.com/openfaas/openfaas-cloud/tree/master/import-secrets

**Comment by alexellis** [comment]
I'm going to cover this @viveksyngh, if you've already started something please review my upcoming PR.

**Comment by viveksyngh** [comment]
Closing this issue as it has been already merged.

**Comment by viveksyngh** [comment]
Derek close
