### ISSUE TITLE
Research: How do we make logs accessible to users?

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#79]
## Feature

There are a couple of scenarios (at least) where we need to make logs available to users:

* Docker build fails for reason X

This should be made available and the GitHub status API only provides a short summary

* git-tar operation fails due to any number of reasons

If the message is short we can store this in the GitHub status

## Related but out of scope in this issue:

* Exposing function logs to users

## Constraints

Can we do this without installing, maintaining and continually migrating a stateful database?

## Potential implementations

* GitHub Gists in user account

* Separate branch in source repository to hold logs

* Separate GitHub repo that we or the user owns

* Use GitHub issues raised in the user's repo

* One GitHub issue and many comments

Or something else completely.

The key point is that we get feedback to the user as a next step, rather than having no logs, how can we get to some logs.

**Comment by rgee0** [comment]
As a code block posted to a user-designated Slack channel? 

Would need to consider rate limiting on the Slack API.  This would likely also be a consideration on other APIs.

**Comment by alexellis** [comment]
Slack URL would have to be a pre-shared secret.. it might not be ideal.

**Comment by alexellis** [comment]
New idea via @stefanprodan - store logs in S3 (i.e. Minio), then a HTML function can render the result for you when you click through from the dashboard overview. Perhaps a regular job could purge old logs?

**Comment by alexellis** [comment]
Example of accessing Minio API - https://github.com/minio/minio-go/blob/master/examples/s3/fputobject.go

**Comment by AkihiroSuda** [comment]
https://transfer.sh/ might be also useful

**Comment by s8sg** [comment]
I can do some research and work on it, if no one is working on this already

**Comment by alexellis** [comment]
I started to look at adapting of-builder to return a JSON body with the image name and an array of log lines, I think that will be part of the work required.

**Comment by s8sg** [comment]
Sounds good.

`time` is something we might want to add. 
It will allow user to figure out the order of `log` for a specific `function` and a specific `commit-sha`

We might hash log by time from `of-builder`
```
"log" : {
    "time+t1" : [ "something something.. ",  "something something.. "],
    "time+t2" : [ "something something.. "],
    ...
    "time+tn" : [ "something something.. "]     
}
```

A logger `sdk` may provide the API to append log to a object and send the log to the `blackbox log function`
the API can be something like the below example
```go

func handle() {
                 
     logger := sdk.NewLogger(gateway, functionname, commit-sha, user)

     //  A api to log a msg, it generate the time autometically
     logger.Log(msg)

     // We can pass the logger object to internal function call if required
     dosomething(logger)

      // This is something we can use of-builder
      // append logs defined as map[time][]logmsg
     logger.AppendLog(logHashedByTime)

     // a single call to report the logs 
     logger.Report()
}
```

The Logger Function API can be 
```
PUT/
{
     "commitId" : "",
     "function" : ""
     "user" : "",
     "logs" : {
          "time-t1" : [ "log1", "log2", "log3" ],
          "time-t2" : [ "log1"],
          ...
      } 
}

GET/
{
   "commitId" : "",
   "function" : "",
   "user" : ""
}
```

**Comment by kvuchkov** [comment]
Another idea might be to leverage the Checks API:
https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com

**Comment by alexellis** [comment]
Derek close: implemented and recorded in roadmap.
