### ISSUE TITLE
Use short SHA for image version

### ISSUE THREAD

**Issue by ivanayov** [openfaas/openfaas-cloud#86]
At the moment the image versions are of type `0.9.1-4456fab11f107a35ee60c4cd3cb6e1e1281cdf95`
e.g.
```
"image": "ofcommunity/kenfdev-faas-contributors-page-contributors-page:0.9.1-4456fab11f107a35ee60c4cd3cb6e1e1281cdf95"
```

As the version is something that's expected to be short in length and the short SHA is enough for commit reference, do you think it's better to cut it?

**Comment by alexellis** [comment]
I don't mind the longer version to be explicit, but am open to changing to the shorter version if you would like to do that work or maybe @viveksyngh? I know there is work in the CLI to generate some tags and that is going to use the short tags, so consistency is probably better. Do you also want to link to that issue for context?

The change should work without clashes.

Alex

**Comment by alexellis** [comment]
On second thoughts I think we should use the format which includes the branch name too - so `--tag=branch` -> https://docs.openfaas.com/cli/tags/

**Comment by alexellis** [comment]
Derek close: duplicates #87
