### ISSUE TITLE
Use faas-cli package for tagging image on OpenFaaS Cloud

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#87]
This new package in faas-cli should be used to create image tags for consistency:

https://github.com/openfaas/faas-cli/blob/master/schema/image.go#L17

It should be a relatively quick change.

**Comment by viveksyngh** [comment]
@alexellis should we vendor `faas-cli` in `openfaas-cloud` and use this package to create tag for images?

**Comment by viveksyngh** [comment]
@alexellis  I have made this changes but recently we have merged PR #85 which validates the images name returned from `buildshiprun` and it's throwing an error for our new image name format. 

I may need help from @s8sg for update the regex to validate image name like this 
`registry:5000/viveksyngh/regex_go-another-go:latest-039ca50585107171bafab71f1d5f65391523cd61`  or should we disable the image name validation and just check for `200` response from `buildshiprun` ?

**Comment by s8sg** [comment]
Otherwise you can change the regex to match the new image name format. As I
told earlier I’m not sure why the image name validation exists

**Comment by viveksyngh** [comment]
I am removing imageName validation and adding response code based validation for `builder` response. If response is not `2xx` we won't get a valid imageName from `builder` and that can be used to deteremine if `build` was successfull or not.

**Comment by viveksyngh** [comment]
@alexellis looks like `image.go` from `schema` package of `faas-cli` is not part of latest release. Should I use `master` to vendor that in `openfaas-cloud` ?

**Comment by s8sg** [comment]
Can you please check if that check if the image id validation is being done
in ofbuilder, And make sure it does gets validated by responses. Otherwise
it might open a closed issue

**Comment by viveksyngh** [comment]
as image check regex got merged to master, I will create a PR to add this support.

**Comment by alexellis** [comment]
Thanks. I've disabled the regex for now. Please PR when you can.
