### ISSUE TITLE
Show OpenFaaS Cloud building a Gist

### ISSUE THREAD

**Issue by alexellis** [openfaas/openfaas-cloud#88]
Since Gists are only GitHub repos, we should support building a function from a Gist.

This is useful because it could become part of play-ground or UI experiment where we can type code into a web-editor which saves into a Gist and triggers a full build-pipeline.

Gists don't appear to support folders, but I may be wrong.

That may mean setting the handler to "./"

## Initial research

First off - try to create a Gist with a stack.yml and a handler of your choice, then clone it and see if you can build it locally with faas-cli.

If you can then see if you can fire a web hook to OpenFaaS cloud with HMAC turned off and fake the JSON data to point at the gist rather than at your GitHub repo - now what is missing/what changes do we need?

Alex

**Comment by viveksyngh** [comment]
Progress: 

Created a https://gist.github.com/viveksyngh/c3d16f0cb5f387c3fc45df6a641c0a8b, cloned it and tried to build the function using CLI. 

Build with CLI was failing, so created a PR to fix that issue here. https://github.com/openfaas/faas-cli/pull/480. Was able to build the function cloned with gist successfully with these changes.

**Comment by alexellis** [comment]
Where are we with this now?

**Comment by martindekov** [comment]
Yeah

**Comment by viveksyngh** [comment]
I have already tried to build a function with CLI manually. I will try to build a function using OpenFaaS-cloud this weekend.

**Comment by alexellis** [comment]
@viveksyngh do you have an update on this please? It may be necessary to fire the event into the `github-push` function manually as I'm not sure if we have a "Gist created" event available for GitHub apps.

**Comment by viveksyngh** [comment]
Yes, We don't have `Gist created` or `Gist Updated` event for Github Apps. I will try to create github-push event manually, see what extra required to build the function using `gist`.

**Comment by alexellis** [comment]
Thanks @viveksyngh I think gist events might be possible through the user permissions section.
