### ISSUE TITLE
git-tar deploy does not return error on non-success http status code

### ISSUE THREAD

**Issue by burtonr** [openfaas/openfaas-cloud#93]
When looking through the logs in `git-tar`, I found that my function deployment returned a 500 error, however, there is no error checking for the deploy status

```
git-tar.1.8qapnsejzztn@playground    | Deploying service - spacex-info
git-tar.1.8qapnsejzztn@playground    | 2018/08/09 02:11:25 v1.53cf333d41169248e81195a8811570348ca18329
git-tar.1.8qapnsejzztn@playground    | Service deployed  spacex-info 500 Internal Server Error burtonr
git-tar.1.8qapnsejzztn@playground    | 2018/08/09 02:11:57 Functions owned by burtonr:
git-tar.1.8qapnsejzztn@playground    |  []Garbage collection ran for burtonr/test-function - 0 functions deleted.
git-tar.1.8qapnsejzztn@playground    | 
git-tar.1.8qapnsejzztn@playground    | 2018/08/09 02:11:58 Duration: 33.223507 seconds
```

The `c.Do(httpReq)` does not throw an error, so this goes unnoticed as the request was successful, but the response status is not success.

See here: https://github.com/openfaas/openfaas-cloud/blob/master/git-tar/function/ops.go#L252

**Comment by ivanayov** [comment]
Just a notice if someone takes this: for both Do and Get, a non-2xx response doesn't cause an error. So this needs an additional check from our side.

**Comment by martindekov** [comment]
Derek close: We have this covered up now https://github.com/openfaas/openfaas-cloud/blob/ab3cb6fef86cf4da7ea2ff69cbc331af553695f5/git-tar/function/ops.go#L409
